<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { FilePlus2, Plus, Trash2 } from 'lucide-vue-next'
import { metadataApi, type AttachmentRecord, type ProofRecord } from '../api/metadata'
import { formatDateTime } from '../utils/date'
import SelectField from './SelectField.vue'
const props=withDefaults(defineProps<{ownerType:'quote'|'order';ownerId:string;protectedContext?:boolean}>(),{protectedContext:false});const emit=defineEmits<{notify:[message:string]}>()
const attachments=ref<AttachmentRecord[]>([]);const proofs=ref<ProofRecord[]>([]);const loading=ref(true);const fileName=ref('');const path=ref('');const category=ref('artwork');const notes=ref('');const proofStatus=ref('Draft');const proofVersion=ref('v1');const proofNote=ref('');const selectedAttachment=ref('');
async function load(){loading.value=true;try{[attachments.value,proofs.value]=await Promise.all([metadataApi.attachments(props.ownerType,props.ownerId),metadataApi.proofs(props.ownerType,props.ownerId)])}catch(e){emit('notify',String(e))}finally{loading.value=false}}
async function addFile(){if(!fileName.value.trim()||!path.value.trim()){emit('notify','Display name and path are required');return}try{await metadataApi.addAttachment({ownerType:props.ownerType,ownerId:props.ownerId,fileName:fileName.value,path:path.value,mimeType:'',sizeBytes:null,checksum:'',category:category.value,notes:notes.value});fileName.value=path.value=notes.value='';await load();emit('notify','Attachment metadata saved')}catch(e){emit('notify',String(e))}}
async function removeFile(id:string){if(props.protectedContext){emit('notify','Attachments on a confirmed document are protected');return}try{await metadataApi.removeAttachment(id);await load();emit('notify','Attachment metadata removed')}catch(e){emit('notify',String(e))}}
async function addProof(){try{await metadataApi.createProof({ownerType:props.ownerType,ownerId:props.ownerId,attachmentId:selectedAttachment.value,status:proofStatus.value,versionLabel:proofVersion.value,approverNote:proofNote.value,internalNote:''});proofNote.value='';await load();emit('notify','Proof version recorded')}catch(e){emit('notify',String(e))}}
onMounted(load)
</script>
<template><div><section><header><div><h2>Files & attachments</h2><p>Metadata and path references only; file bytes stay outside SQLite.</p></div><FilePlus2 :size="17"/></header><div><input class="input input-bordered w-full min-w-0" v-model="fileName" placeholder="Display name"/><input class="input input-bordered w-full min-w-0" v-model="path" placeholder="Relative or external path"/><SelectField v-model="category" label="Category" :options="[{ label: 'Artwork', value: 'artwork' }, { label: 'Proof', value: 'proof' }, { label: 'Reference', value: 'reference' }, { label: 'Other', value: 'other' }]"/><input class="input input-bordered w-full min-w-0" v-model="notes" placeholder="Notes"/><button class="btn btn-ghost" @click="addFile"><Plus :size="14"/>Add metadata</button></div><div v-if="loading">Loading metadata…</div><div v-else-if="!attachments.length">No attachment metadata yet.</div><div v-for="file in attachments" :key="file.id"><div><strong>{{ file.fileName }}</strong><span>{{ file.category }} · {{ file.path }}</span><small v-if="file.notes">{{ file.notes }}</small></div><button class="btn btn-ghost" aria-label="Remove attachment metadata" @click="removeFile(file.id)"><Trash2 :size="14"/></button></div></section><section><header><div><h2>Proof history</h2><p>Every status entry is a preserved version of the proof record.</p></div></header><div><input class="input input-bordered w-full min-w-0" v-model="proofVersion" placeholder="Version / label"/><SelectField v-model="selectedAttachment" label="Related attachment" :options="[{ label: 'No related attachment', value: '' }, ...attachments.map((file) => ({ label: file.fileName, value: file.id }))]"/><SelectField v-model="proofStatus" label="Status" :options="['Draft', 'Ready', 'Waiting Customer Approval', 'Approved', 'Rejected'].map((value) => ({ label: value, value }))"/><input class="input input-bordered w-full min-w-0" v-model="proofNote" placeholder="Approval / rejection note"/><button class="btn btn-ghost" @click="addProof"><Plus :size="14"/>Record version</button></div><div v-if="!proofs.length">No proof versions recorded yet.</div><div v-for="proof in proofs" :key="proof.id"><div><strong>{{ proof.versionLabel }} · {{ proof.status }}</strong><span>{{ proof.createdAt ? formatDateTime(proof.createdAt) : '' }}</span><small v-if="proof.approverNote">{{ proof.approverNote }}</small></div></div></section></div></template>
