import fs from 'node:fs/promises'
import assert from 'node:assert/strict'
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']})
const output='/tmp/atropaten-ui-interactions';await fs.mkdir(output,{recursive:true})
const results=[]
for(const width of [1024,1280,1600]) {
 const page=await browser.newPage({viewport:{width,height:1000}})
 const errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.clock.setFixedTime(new Date('2026-03-21T12:00:00Z'))
 await page.addInitScript(()=>{window.go={main:{App:new Proxy({},{get:(_,name)=>async(...args)=>{const r=await fetch('http://127.0.0.1:4174/call/'+String(name),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(args)});if(!r.ok)throw new Error(await r.text());return r.json()}})}}})
 await page.goto('http://127.0.0.1:5178');await page.waitForTimeout(900)
 const nav=async name=>{await page.getByRole('button',{name,exact:true}).first().click();await page.waitForTimeout(350)}
 const shot=async name=>{await page.screenshot({path:`${output}/${width}-${name}.png`});results.push({width,state:name,overflow:await page.evaluate(()=>document.querySelector('main').scrollWidth>document.querySelector('main').clientWidth)})}
 await nav('Customers')
 await page.getByRole('button',{name:'New customer',exact:true}).click()
 const name=page.getByLabel('Customer name',{exact:true})
 await name.fill('آزمایش رابط کاربری — نام بسیار طولانی برای بررسی فرم و فاصله‌ها '+width)
 const geometry=await name.evaluate(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height,border:getComputedStyle(e).borderStyle,shadow:getComputedStyle(e).boxShadow,outline:getComputedStyle(e).outlineStyle}))
 assert.equal(geometry.border,'dashed');assert.equal(geometry.shadow,'none');assert.equal(geometry.outline,'none')
 await shot('customer-form-focus')
 await page.getByLabel('Email',{exact:true}).fill('audit@example.invalid')
 let attempts=0
 await page.route('**/call/CreateCustomer',async route=>{attempts++;await new Promise(r=>setTimeout(r,400));await route.fulfill({status:400,contentType:'text/plain',body:'Injected validation error: customer name rejected',headers:{'Access-Control-Allow-Origin':'http://127.0.0.1:5178'}})})
 await page.getByRole('button',{name:'Save customer',exact:true}).click()
 assert.equal(await page.getByRole('button',{name:/Saving|Save customer/}).last().isDisabled(),true)
 await page.waitForTimeout(550)
 assert.equal(attempts,1);assert.match(await name.inputValue(),/آزمایش/)
 assert.equal(await page.locator('.toast .alert-error').count(),1)
 assert.equal(await page.locator('.toast .alert-success').count(),0)
 await shot('validation-error-preserves-form')
 await page.unroute('**/call/CreateCustomer')
 await page.getByRole('button',{name:'Save customer',exact:true}).click();await page.waitForTimeout(500)
 assert.ok(await page.locator('.toast .alert-success').count()>0)
 await shot('success-toast')
 await page.getByRole('button',{name:'Delete',exact:true}).click()
 await page.locator('dialog[open]').waitFor()
 assert.equal(await page.locator('dialog[open]').evaluate(e=>e.contains(document.activeElement)),true)
 await shot('confirmation-dialog')
 await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0)
 await page.getByLabel('Search customers',{exact:true}).fill('NO-MATCH-UI-AUDIT')
 await shot('customer-empty')
 await nav('Materials');await page.getByRole('button',{name:'New material',exact:true}).click();await shot('material-editor')
 await nav('Orders');await page.getByRole('button',{name:'ORD-1004',exact:true}).click();await page.waitForTimeout(250);await shot('order-editor')
 await page.getByRole('button',{name:'Open Jalali calendar',exact:true}).first().click();await shot('jalali-calendar');await page.keyboard.press('Escape')
 await page.getByRole('tab',{name:'Items',exact:true}).click();await shot('order-items')
 await nav('Quotes');await page.locator('main [role="button"]').first().click();await shot('quote-editor')
 await nav('Accounting')
 for(const tab of ['Accounts','Journal','Payments','Expenses','Transfers / Treasury']) {await page.getByRole('tab',{name:tab,exact:true}).click();await page.waitForTimeout(200);await shot('accounting-'+tab.split(' ')[0].toLowerCase())}
 await nav('Loans');await page.getByRole('button',{name:'All',exact:true}).click();await shot('loans-populated');await page.getByRole('button',{name:'New loan',exact:true}).click();await shot('loan-form')
 await nav('Checks');await page.getByRole('button',{name:'New check',exact:true}).click();await shot('check-form')
 await nav('Owners');await page.getByRole('button',{name:'Owners',exact:true}).last().click();await shot('owners-register')
 await nav('Services');await page.getByRole('button',{name:'New service',exact:true}).click();await shot('service-form')
 await page.getByRole('button',{name:'Add parameter',exact:true}).click();await shot('service-parameter-editor')
 await nav('Reports');await page.getByLabel('Record ID',{exact:true}).fill('INV-DEMO-01');await page.getByRole('button',{name:'Load preview',exact:true}).click();await page.waitForTimeout(350);await shot('print-preview')
 assert.ok(await page.locator('.print-document').count()===2)
 await page.emulateMedia({media:'print'});assert.equal(await page.locator('#app').isVisible(),false);assert.equal(await page.locator('.print-output').isVisible(),true)
 if(width===1280)await page.pdf({path:`${output}/invoice-preview.pdf`,format:'A4',printBackground:true})
 await page.emulateMedia({media:'screen'})
 await page.route('**/call/ListCustomers',async route=>{await new Promise(r=>setTimeout(r,700));await route.continue()})
 await page.getByRole('button',{name:'Customers',exact:true}).first().click();await page.waitForTimeout(80);await shot('loading');await page.waitForTimeout(800);await page.unroute('**/call/ListCustomers')
 await page.route('**/call/ListMaterials',route=>route.fulfill({status:500,body:'Injected materials load failure',headers:{'Access-Control-Allow-Origin':'http://127.0.0.1:5178'}}))
 await nav('Materials');await shot('page-error');assert.ok(await page.getByRole('alert').filter({hasText:'Injected materials'}).count())
 assert.deepEqual(errors,[])
 await page.close()
}
await browser.close();await fs.writeFile(`${output}/results.json`,JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2))
