// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServiceParameter(arg1, arg2) {
  return window['go']['main']['App']['AddServiceParameter'](arg1, arg2);
}

export function ArchiveMaterial(arg1) {
  return window['go']['main']['App']['ArchiveMaterial'](arg1);
}

export function ArchiveService(arg1) {
  return window['go']['main']['App']['ArchiveService'](arg1);
}

export function CreateMaterial(arg1) {
  return window['go']['main']['App']['CreateMaterial'](arg1);
}

export function CreateService(arg1) {
  return window['go']['main']['App']['CreateService'](arg1);
}

export function GetMaterial(arg1) {
  return window['go']['main']['App']['GetMaterial'](arg1);
}

export function GetService(arg1) {
  return window['go']['main']['App']['GetService'](arg1);
}

export function ListMaterials(arg1) {
  return window['go']['main']['App']['ListMaterials'](arg1);
}

export function ListServices(arg1) {
  return window['go']['main']['App']['ListServices'](arg1);
}

export function ReactivateMaterial(arg1) {
  return window['go']['main']['App']['ReactivateMaterial'](arg1);
}

export function ReactivateService(arg1) {
  return window['go']['main']['App']['ReactivateService'](arg1);
}

export function RemoveServiceParameter(arg1, arg2) {
  return window['go']['main']['App']['RemoveServiceParameter'](arg1, arg2);
}

export function ReorderServiceParameters(arg1, arg2) {
  return window['go']['main']['App']['ReorderServiceParameters'](arg1, arg2);
}

export function UpdateMaterial(arg1, arg2) {
  return window['go']['main']['App']['UpdateMaterial'](arg1, arg2);
}

export function UpdateService(arg1, arg2) {
  return window['go']['main']['App']['UpdateService'](arg1, arg2);
}

export function UpdateServiceParameter(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateServiceParameter'](arg1, arg2, arg3);
}
