// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAttachment(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:any,arg7:string,arg8:string,arg9:string):Promise<main.AttachmentDTO>;

export function AddOrderItem(arg1:string,arg2:main.OrderItemInput):Promise<main.OrderDTO>;

export function AddQuoteItem(arg1:string,arg2:main.OrderItemInput):Promise<main.QuoteDTO>;

export function AddServiceCostComponent(arg1:string,arg2:main.ServiceCostComponentInput):Promise<main.ServiceDTO>;

export function AddServiceParameter(arg1:string,arg2:main.ServiceParameterInput):Promise<main.ServiceDTO>;

export function ApplyOrderDiscount(arg1:string,arg2:number):Promise<main.OrderDTO>;

export function ApplyQuoteDiscount(arg1:string,arg2:number):Promise<main.QuoteDTO>;

export function ArchiveCustomer(arg1:string):Promise<main.CustomerDTO>;

export function ArchiveMachine(arg1:string):Promise<main.MachineDTO>;

export function ArchiveMaterial(arg1:string):Promise<main.MaterialDTO>;

export function ArchiveService(arg1:string):Promise<main.ServiceDTO>;

export function CalculateServicePrice(arg1:main.PricingRequest):Promise<main.PricingDTO>;

export function ConvertQuoteToOrder(arg1:string):Promise<main.QuoteDTO>;

export function CreateCustomer(arg1:main.CustomerInput):Promise<main.CustomerDTO>;

export function CreateMachine(arg1:main.MachineInput):Promise<main.MachineDTO>;

export function CreateMaterial(arg1:main.MaterialInput):Promise<main.MaterialDTO>;

export function CreateOrder(arg1:main.OrderInput):Promise<main.OrderDTO>;

export function CreateProof(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<main.ProofDTO>;

export function CreateQuote(arg1:main.QuoteInput):Promise<main.QuoteDTO>;

export function CreateService(arg1:main.ServiceInput):Promise<main.ServiceDTO>;

export function GetCustomer(arg1:string):Promise<main.CustomerDTO>;

export function GetMachine(arg1:string):Promise<main.MachineDTO>;

export function GetMaterial(arg1:string):Promise<main.MaterialDTO>;

export function GetOrder(arg1:string):Promise<main.OrderDTO>;

export function GetQuote(arg1:string):Promise<main.QuoteDTO>;

export function GetService(arg1:string):Promise<main.ServiceDTO>;

export function ListAttachments(arg1:string,arg2:string):Promise<Array<main.AttachmentDTO>>;

export function ListCustomers(arg1:boolean):Promise<Array<main.CustomerDTO>>;

export function ListMachines(arg1:boolean):Promise<Array<main.MachineDTO>>;

export function ListMaterials(arg1:boolean):Promise<Array<main.MaterialDTO>>;

export function ListOrders():Promise<Array<main.OrderDTO>>;

export function ListProofs(arg1:string,arg2:string):Promise<Array<main.ProofDTO>>;

export function ListQuotes():Promise<Array<main.QuoteDTO>>;

export function ListServices(arg1:boolean):Promise<Array<main.ServiceDTO>>;

export function ListSuppliers(arg1:boolean):Promise<any[]>;
export function GetSupplier(arg1:string):Promise<any>;
export function CreateSupplier(arg1:any):Promise<any>;
export function UpdateSupplier(arg1:string,arg2:any):Promise<any>;
export function ArchiveSupplier(arg1:string):Promise<any>;
export function ReactivateSupplier(arg1:string):Promise<any>;
export function DeleteSupplier(arg1:string):Promise<void>;
export function ListPurchases():Promise<any[]>;
export function GetPurchase(arg1:string):Promise<any>;
export function CreatePurchase(arg1:any):Promise<any>;
export function UpdatePurchase(arg1:string,arg2:any):Promise<any>;
export function AddPurchaseItem(arg1:string,arg2:any):Promise<any>;
export function UpdatePurchaseItem(arg1:string,arg2:string,arg3:any):Promise<any>;
export function RemovePurchaseItem(arg1:string,arg2:string):Promise<any>;
export function ReorderPurchaseItems(arg1:string,arg2:string[]):Promise<any>;
export function PostPurchase(arg1:string):Promise<any>;
export function CancelPurchase(arg1:string):Promise<any>;
export function DeleteDraftPurchase(arg1:string):Promise<void>;
export function ListMaterialMovements(arg1:string):Promise<any[]>;
export function AdjustMaterialStock(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function ReactivateCustomer(arg1:string):Promise<main.CustomerDTO>;

export function ReactivateMachine(arg1:string):Promise<main.MachineDTO>;

export function ReactivateMaterial(arg1:string):Promise<main.MaterialDTO>;

export function ReactivateService(arg1:string):Promise<main.ServiceDTO>;

export function RemoveAttachment(arg1:string):Promise<void>;

export function RemoveOrderItem(arg1:string,arg2:string):Promise<main.OrderDTO>;

export function RemoveQuoteItem(arg1:string,arg2:string):Promise<main.QuoteDTO>;

export function RemoveServiceCostComponent(arg1:string,arg2:string):Promise<main.ServiceDTO>;

export function RemoveServiceParameter(arg1:string,arg2:string):Promise<main.ServiceDTO>;

export function ReorderOrderItems(arg1:string,arg2:Array<string>):Promise<main.OrderDTO>;

export function ReorderQuoteItems(arg1:string,arg2:Array<string>):Promise<main.QuoteDTO>;

export function ReorderServiceCostComponents(arg1:string,arg2:Array<string>):Promise<main.ServiceDTO>;

export function ReorderServiceParameters(arg1:string,arg2:Array<string>):Promise<main.ServiceDTO>;

export function ReplaceOrderItem(arg1:string,arg2:string,arg3:main.OrderItemInput):Promise<main.OrderDTO>;

export function ReplaceQuoteItem(arg1:string,arg2:string,arg3:main.OrderItemInput):Promise<main.QuoteDTO>;

export function UpdateCustomer(arg1:string,arg2:main.CustomerInput):Promise<main.CustomerDTO>;

export function UpdateMachine(arg1:string,arg2:main.MachineInput):Promise<main.MachineDTO>;

export function UpdateMaterial(arg1:string,arg2:main.MaterialInput):Promise<main.MaterialDTO>;

export function UpdateOrder(arg1:string,arg2:main.OrderInput):Promise<main.OrderDTO>;

export function UpdateOrderCommercialStatus(arg1:string,arg2:string):Promise<main.OrderDTO>;

export function UpdateOrderFulfillmentStatus(arg1:string,arg2:string):Promise<main.OrderDTO>;

export function UpdateProofStatus(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.ProofDTO>;

export function UpdateQuote(arg1:string,arg2:main.QuoteInput):Promise<main.QuoteDTO>;

export function UpdateQuoteStatus(arg1:string,arg2:string):Promise<main.QuoteDTO>;

export function UpdateService(arg1:string,arg2:main.ServiceInput):Promise<main.ServiceDTO>;

export function UpdateServiceCostComponent(arg1:string,arg2:string,arg3:main.ServiceCostComponentInput):Promise<main.ServiceDTO>;

export function UpdateServiceParameter(arg1:string,arg2:string,arg3:main.ServiceParameterInput):Promise<main.ServiceDTO>;
