// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAttachment(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['AddAttachment'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function AddOrderItem(arg1, arg2) {
  return window['go']['main']['App']['AddOrderItem'](arg1, arg2);
}

export function AddPurchaseItem(arg1, arg2) {
  return window['go']['main']['App']['AddPurchaseItem'](arg1, arg2);
}

export function AddQuoteItem(arg1, arg2) {
  return window['go']['main']['App']['AddQuoteItem'](arg1, arg2);
}

export function AddServiceCostComponent(arg1, arg2) {
  return window['go']['main']['App']['AddServiceCostComponent'](arg1, arg2);
}

export function AddServiceParameter(arg1, arg2) {
  return window['go']['main']['App']['AddServiceParameter'](arg1, arg2);
}

export function AdjustMaterialStock(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AdjustMaterialStock'](arg1, arg2, arg3, arg4);
}

export function ApplyOrderDiscount(arg1, arg2) {
  return window['go']['main']['App']['ApplyOrderDiscount'](arg1, arg2);
}

export function ApplyQuoteDiscount(arg1, arg2) {
  return window['go']['main']['App']['ApplyQuoteDiscount'](arg1, arg2);
}

export function ArchiveCustomer(arg1) {
  return window['go']['main']['App']['ArchiveCustomer'](arg1);
}

export function ArchiveMachine(arg1) {
  return window['go']['main']['App']['ArchiveMachine'](arg1);
}

export function ArchiveMaterial(arg1) {
  return window['go']['main']['App']['ArchiveMaterial'](arg1);
}

export function ArchiveService(arg1) {
  return window['go']['main']['App']['ArchiveService'](arg1);
}

export function ArchiveSupplier(arg1) {
  return window['go']['main']['App']['ArchiveSupplier'](arg1);
}

export function CalculateServicePrice(arg1) {
  return window['go']['main']['App']['CalculateServicePrice'](arg1);
}

export function CancelPurchase(arg1) {
  return window['go']['main']['App']['CancelPurchase'](arg1);
}

export function ConvertQuoteToOrder(arg1) {
  return window['go']['main']['App']['ConvertQuoteToOrder'](arg1);
}

export function CreateCustomer(arg1) {
  return window['go']['main']['App']['CreateCustomer'](arg1);
}

export function CreateExpense(arg1) {
  return window['go']['main']['App']['CreateExpense'](arg1);
}

export function CreateInventoryReservation(arg1) {
  return window['go']['main']['App']['CreateInventoryReservation'](arg1);
}

export function CreateInvoiceFromOrder(arg1) {
  return window['go']['main']['App']['CreateInvoiceFromOrder'](arg1);
}

export function CreateMachine(arg1) {
  return window['go']['main']['App']['CreateMachine'](arg1);
}

export function CreateMaterial(arg1) {
  return window['go']['main']['App']['CreateMaterial'](arg1);
}

export function CreateOrder(arg1) {
  return window['go']['main']['App']['CreateOrder'](arg1);
}

export function CreatePayment(arg1) {
  return window['go']['main']['App']['CreatePayment'](arg1);
}

export function CreateProductionJob(arg1) {
  return window['go']['main']['App']['CreateProductionJob'](arg1);
}

export function CreateProof(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateProof'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreatePurchase(arg1) {
  return window['go']['main']['App']['CreatePurchase'](arg1);
}

export function CreateQuote(arg1) {
  return window['go']['main']['App']['CreateQuote'](arg1);
}

export function CreateService(arg1) {
  return window['go']['main']['App']['CreateService'](arg1);
}

export function CreateSupplier(arg1) {
  return window['go']['main']['App']['CreateSupplier'](arg1);
}

export function CreateTransfer(arg1) {
  return window['go']['main']['App']['CreateTransfer'](arg1);
}

export function DeleteDraftInvoice(arg1) {
  return window['go']['main']['App']['DeleteDraftInvoice'](arg1);
}

export function DeleteDraftPurchase(arg1) {
  return window['go']['main']['App']['DeleteDraftPurchase'](arg1);
}

export function DeleteProductionJob(arg1) {
  return window['go']['main']['App']['DeleteProductionJob'](arg1);
}

export function DeleteSupplier(arg1) {
  return window['go']['main']['App']['DeleteSupplier'](arg1);
}

export function GetCustomer(arg1) {
  return window['go']['main']['App']['GetCustomer'](arg1);
}

export function GetCustomerFinancialSummary(arg1) {
  return window['go']['main']['App']['GetCustomerFinancialSummary'](arg1);
}

export function GetInvoice(arg1) {
  return window['go']['main']['App']['GetInvoice'](arg1);
}

export function GetMachine(arg1) {
  return window['go']['main']['App']['GetMachine'](arg1);
}

export function GetMaterial(arg1) {
  return window['go']['main']['App']['GetMaterial'](arg1);
}

export function GetOrder(arg1) {
  return window['go']['main']['App']['GetOrder'](arg1);
}

export function GetProductionJob(arg1) {
  return window['go']['main']['App']['GetProductionJob'](arg1);
}

export function GetPurchase(arg1) {
  return window['go']['main']['App']['GetPurchase'](arg1);
}

export function GetQuote(arg1) {
  return window['go']['main']['App']['GetQuote'](arg1);
}

export function GetService(arg1) {
  return window['go']['main']['App']['GetService'](arg1);
}

export function GetSupplier(arg1) {
  return window['go']['main']['App']['GetSupplier'](arg1);
}

export function GetSupplierPayableBalance(arg1) {
  return window['go']['main']['App']['GetSupplierPayableBalance'](arg1);
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListAttachments(arg1, arg2) {
  return window['go']['main']['App']['ListAttachments'](arg1, arg2);
}

export function ListCustomers(arg1) {
  return window['go']['main']['App']['ListCustomers'](arg1);
}

export function ListExpenses() {
  return window['go']['main']['App']['ListExpenses']();
}

export function ListFinancialAccounts() {
  return window['go']['main']['App']['ListFinancialAccounts']();
}

export function ListInventoryReservations(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListInventoryReservations'](arg1, arg2, arg3);
}

export function ListInvoices() {
  return window['go']['main']['App']['ListInvoices']();
}

export function ListJournalEntries() {
  return window['go']['main']['App']['ListJournalEntries']();
}

export function ListMachines(arg1) {
  return window['go']['main']['App']['ListMachines'](arg1);
}

export function ListMaterialMovements(arg1) {
  return window['go']['main']['App']['ListMaterialMovements'](arg1);
}

export function ListMaterials(arg1) {
  return window['go']['main']['App']['ListMaterials'](arg1);
}

export function ListOrders() {
  return window['go']['main']['App']['ListOrders']();
}

export function ListPayments() {
  return window['go']['main']['App']['ListPayments']();
}

export function ListProductionConsumptions(arg1) {
  return window['go']['main']['App']['ListProductionConsumptions'](arg1);
}

export function ListProductionJobs(arg1) {
  return window['go']['main']['App']['ListProductionJobs'](arg1);
}

export function ListProofs(arg1, arg2) {
  return window['go']['main']['App']['ListProofs'](arg1, arg2);
}

export function ListPurchases() {
  return window['go']['main']['App']['ListPurchases']();
}

export function ListQuotes() {
  return window['go']['main']['App']['ListQuotes']();
}

export function ListServices(arg1) {
  return window['go']['main']['App']['ListServices'](arg1);
}

export function ListSuppliers(arg1) {
  return window['go']['main']['App']['ListSuppliers'](arg1);
}

export function ListTransfers() {
  return window['go']['main']['App']['ListTransfers']();
}

export function PostInvoice(arg1) {
  return window['go']['main']['App']['PostInvoice'](arg1);
}

export function PostPurchase(arg1) {
  return window['go']['main']['App']['PostPurchase'](arg1);
}

export function ReactivateCustomer(arg1) {
  return window['go']['main']['App']['ReactivateCustomer'](arg1);
}

export function ReactivateMachine(arg1) {
  return window['go']['main']['App']['ReactivateMachine'](arg1);
}

export function ReactivateMaterial(arg1) {
  return window['go']['main']['App']['ReactivateMaterial'](arg1);
}

export function ReactivateService(arg1) {
  return window['go']['main']['App']['ReactivateService'](arg1);
}

export function ReactivateSupplier(arg1) {
  return window['go']['main']['App']['ReactivateSupplier'](arg1);
}

export function RecordProductionConsumption(arg1, arg2) {
  return window['go']['main']['App']['RecordProductionConsumption'](arg1, arg2);
}

export function ReleaseInventoryReservation(arg1) {
  return window['go']['main']['App']['ReleaseInventoryReservation'](arg1);
}

export function RemoveAttachment(arg1) {
  return window['go']['main']['App']['RemoveAttachment'](arg1);
}

export function RemoveOrderItem(arg1, arg2) {
  return window['go']['main']['App']['RemoveOrderItem'](arg1, arg2);
}

export function RemovePurchaseItem(arg1, arg2) {
  return window['go']['main']['App']['RemovePurchaseItem'](arg1, arg2);
}

export function RemoveQuoteItem(arg1, arg2) {
  return window['go']['main']['App']['RemoveQuoteItem'](arg1, arg2);
}

export function RemoveServiceCostComponent(arg1, arg2) {
  return window['go']['main']['App']['RemoveServiceCostComponent'](arg1, arg2);
}

export function RemoveServiceParameter(arg1, arg2) {
  return window['go']['main']['App']['RemoveServiceParameter'](arg1, arg2);
}

export function ReorderOrderItems(arg1, arg2) {
  return window['go']['main']['App']['ReorderOrderItems'](arg1, arg2);
}

export function ReorderPurchaseItems(arg1, arg2) {
  return window['go']['main']['App']['ReorderPurchaseItems'](arg1, arg2);
}

export function ReorderQuoteItems(arg1, arg2) {
  return window['go']['main']['App']['ReorderQuoteItems'](arg1, arg2);
}

export function ReorderServiceCostComponents(arg1, arg2) {
  return window['go']['main']['App']['ReorderServiceCostComponents'](arg1, arg2);
}

export function ReorderServiceParameters(arg1, arg2) {
  return window['go']['main']['App']['ReorderServiceParameters'](arg1, arg2);
}

export function ReplaceOrderItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReplaceOrderItem'](arg1, arg2, arg3);
}

export function ReplaceQuoteItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReplaceQuoteItem'](arg1, arg2, arg3);
}

export function ReverseExpense(arg1, arg2) {
  return window['go']['main']['App']['ReverseExpense'](arg1, arg2);
}

export function ReversePayment(arg1, arg2) {
  return window['go']['main']['App']['ReversePayment'](arg1, arg2);
}

export function ReverseProductionConsumption(arg1, arg2) {
  return window['go']['main']['App']['ReverseProductionConsumption'](arg1, arg2);
}

export function ReverseTransfer(arg1, arg2) {
  return window['go']['main']['App']['ReverseTransfer'](arg1, arg2);
}

export function UpdateCustomer(arg1, arg2) {
  return window['go']['main']['App']['UpdateCustomer'](arg1, arg2);
}

export function UpdateInventoryReservation(arg1, arg2) {
  return window['go']['main']['App']['UpdateInventoryReservation'](arg1, arg2);
}

export function UpdateMachine(arg1, arg2) {
  return window['go']['main']['App']['UpdateMachine'](arg1, arg2);
}

export function UpdateMaterial(arg1, arg2) {
  return window['go']['main']['App']['UpdateMaterial'](arg1, arg2);
}

export function UpdateOrder(arg1, arg2) {
  return window['go']['main']['App']['UpdateOrder'](arg1, arg2);
}

export function UpdateOrderCommercialStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateOrderCommercialStatus'](arg1, arg2);
}

export function UpdateOrderFulfillmentStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateOrderFulfillmentStatus'](arg1, arg2);
}

export function UpdateProductionJob(arg1, arg2) {
  return window['go']['main']['App']['UpdateProductionJob'](arg1, arg2);
}

export function UpdateProductionJobStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateProductionJobStatus'](arg1, arg2);
}

export function UpdateProductionOutsourcing(arg1, arg2) {
  return window['go']['main']['App']['UpdateProductionOutsourcing'](arg1, arg2);
}

export function UpdateProofStatus(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateProofStatus'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdatePurchase(arg1, arg2) {
  return window['go']['main']['App']['UpdatePurchase'](arg1, arg2);
}

export function UpdatePurchaseItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePurchaseItem'](arg1, arg2, arg3);
}

export function UpdateQuote(arg1, arg2) {
  return window['go']['main']['App']['UpdateQuote'](arg1, arg2);
}

export function UpdateQuoteStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateQuoteStatus'](arg1, arg2);
}

export function UpdateService(arg1, arg2) {
  return window['go']['main']['App']['UpdateService'](arg1, arg2);
}

export function UpdateServiceCostComponent(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateServiceCostComponent'](arg1, arg2, arg3);
}

export function UpdateServiceParameter(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateServiceParameter'](arg1, arg2, arg3);
}

export function UpdateSupplier(arg1, arg2) {
  return window['go']['main']['App']['UpdateSupplier'](arg1, arg2);
}

export function VoidInvoice(arg1) {
  return window['go']['main']['App']['VoidInvoice'](arg1);
}
