// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOrderItem(arg1, arg2) {
  return window['go']['main']['App']['AddOrderItem'](arg1, arg2);
}

export function AddServiceCostComponent(arg1, arg2) {
  return window['go']['main']['App']['AddServiceCostComponent'](arg1, arg2);
}

export function AddServiceParameter(arg1, arg2) {
  return window['go']['main']['App']['AddServiceParameter'](arg1, arg2);
}

export function ApplyOrderDiscount(arg1, arg2) {
  return window['go']['main']['App']['ApplyOrderDiscount'](arg1, arg2);
}

export function ArchiveCustomer(arg1) {
  return window['go']['main']['App']['ArchiveCustomer'](arg1);
}

export function ArchiveMachine(arg1) {
  return window['go']['main']['App']['ArchiveMachine'](arg1);
}

export function ArchiveMaterial(arg1) {
  return window['go']['main']['App']['ArchiveMaterial'](arg1);
}

export function ArchiveService(arg1) {
  return window['go']['main']['App']['ArchiveService'](arg1);
}

export function CalculateServicePrice(arg1) {
  return window['go']['main']['App']['CalculateServicePrice'](arg1);
}

export function CreateCustomer(arg1) {
  return window['go']['main']['App']['CreateCustomer'](arg1);
}

export function CreateMachine(arg1) {
  return window['go']['main']['App']['CreateMachine'](arg1);
}

export function CreateMaterial(arg1) {
  return window['go']['main']['App']['CreateMaterial'](arg1);
}

export function CreateOrder(arg1) {
  return window['go']['main']['App']['CreateOrder'](arg1);
}

export function CreateService(arg1) {
  return window['go']['main']['App']['CreateService'](arg1);
}

export function GetCustomer(arg1) {
  return window['go']['main']['App']['GetCustomer'](arg1);
}

export function GetMachine(arg1) {
  return window['go']['main']['App']['GetMachine'](arg1);
}

export function GetMaterial(arg1) {
  return window['go']['main']['App']['GetMaterial'](arg1);
}

export function GetOrder(arg1) {
  return window['go']['main']['App']['GetOrder'](arg1);
}

export function GetService(arg1) {
  return window['go']['main']['App']['GetService'](arg1);
}

export function ListCustomers(arg1) {
  return window['go']['main']['App']['ListCustomers'](arg1);
}

export function ListMachines(arg1) {
  return window['go']['main']['App']['ListMachines'](arg1);
}

export function ListMaterials(arg1) {
  return window['go']['main']['App']['ListMaterials'](arg1);
}

export function ListOrders() {
  return window['go']['main']['App']['ListOrders']();
}

export function ListServices(arg1) {
  return window['go']['main']['App']['ListServices'](arg1);
}

export function ReactivateCustomer(arg1) {
  return window['go']['main']['App']['ReactivateCustomer'](arg1);
}

export function ReactivateMachine(arg1) {
  return window['go']['main']['App']['ReactivateMachine'](arg1);
}

export function ReactivateMaterial(arg1) {
  return window['go']['main']['App']['ReactivateMaterial'](arg1);
}

export function ReactivateService(arg1) {
  return window['go']['main']['App']['ReactivateService'](arg1);
}

export function RemoveOrderItem(arg1, arg2) {
  return window['go']['main']['App']['RemoveOrderItem'](arg1, arg2);
}

export function RemoveServiceCostComponent(arg1, arg2) {
  return window['go']['main']['App']['RemoveServiceCostComponent'](arg1, arg2);
}

export function RemoveServiceParameter(arg1, arg2) {
  return window['go']['main']['App']['RemoveServiceParameter'](arg1, arg2);
}

export function ReorderOrderItems(arg1, arg2) {
  return window['go']['main']['App']['ReorderOrderItems'](arg1, arg2);
}

export function ReorderServiceCostComponents(arg1, arg2) {
  return window['go']['main']['App']['ReorderServiceCostComponents'](arg1, arg2);
}

export function ReorderServiceParameters(arg1, arg2) {
  return window['go']['main']['App']['ReorderServiceParameters'](arg1, arg2);
}

export function ReplaceOrderItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReplaceOrderItem'](arg1, arg2, arg3);
}

export function UpdateCustomer(arg1, arg2) {
  return window['go']['main']['App']['UpdateCustomer'](arg1, arg2);
}

export function UpdateMachine(arg1, arg2) {
  return window['go']['main']['App']['UpdateMachine'](arg1, arg2);
}

export function UpdateMaterial(arg1, arg2) {
  return window['go']['main']['App']['UpdateMaterial'](arg1, arg2);
}

export function UpdateOrder(arg1, arg2) {
  return window['go']['main']['App']['UpdateOrder'](arg1, arg2);
}

export function UpdateOrderCommercialStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateOrderCommercialStatus'](arg1, arg2);
}

export function UpdateOrderFulfillmentStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateOrderFulfillmentStatus'](arg1, arg2);
}

export function UpdateService(arg1, arg2) {
  return window['go']['main']['App']['UpdateService'](arg1, arg2);
}

export function UpdateServiceCostComponent(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateServiceCostComponent'](arg1, arg2, arg3);
}

export function UpdateServiceParameter(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateServiceParameter'](arg1, arg2, arg3);
}
