// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAttachment(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:any,arg7:string,arg8:string,arg9:string):Promise<main.AttachmentDTO>;

export function AddOrderItem(arg1:string,arg2:main.OrderItemInput):Promise<main.OrderDTO>;

export function AddPurchaseItem(arg1:string,arg2:main.PurchaseItemInput):Promise<main.PurchaseDTO>;

export function AddQuoteItem(arg1:string,arg2:main.OrderItemInput):Promise<main.QuoteDTO>;

export function AddServiceCostComponent(arg1:string,arg2:main.ServiceCostComponentInput):Promise<main.ServiceDTO>;

export function AddServiceParameter(arg1:string,arg2:main.ServiceParameterInput):Promise<main.ServiceDTO>;

export function AdjustMaterialStock(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function ApplyOrderDiscount(arg1:string,arg2:number):Promise<main.OrderDTO>;

export function ApplyQuoteDiscount(arg1:string,arg2:number):Promise<main.QuoteDTO>;

export function ArchiveCustomer(arg1:string):Promise<main.CustomerDTO>;

export function ArchiveMachine(arg1:string):Promise<main.MachineDTO>;

export function ArchiveMaterial(arg1:string):Promise<main.MaterialDTO>;

export function ArchiveService(arg1:string):Promise<main.ServiceDTO>;

export function ArchiveSupplier(arg1:string):Promise<main.SupplierDTO>;

export function CalculateServicePrice(arg1:main.PricingRequest):Promise<main.PricingDTO>;

export function CancelPurchase(arg1:string):Promise<main.PurchaseDTO>;

export function ConvertQuoteToOrder(arg1:string):Promise<main.QuoteDTO>;

export function CreateCustomer(arg1:main.CustomerInput):Promise<main.CustomerDTO>;

export function CreateExpense(arg1:main.ExpenseInputDTO):Promise<main.ExpenseDTO>;

export function CreateInventoryReservation(arg1:main.InventoryReservationInput):Promise<main.InventoryReservationDTO>;

export function CreateInvoiceFromOrder(arg1:string):Promise<main.InvoiceDTO>;

export function CreateMachine(arg1:main.MachineInput):Promise<main.MachineDTO>;

export function CreateMaterial(arg1:main.MaterialInput):Promise<main.MaterialDTO>;

export function CreateOrder(arg1:main.OrderInput):Promise<main.OrderDTO>;

export function CreatePayment(arg1:main.PaymentInputDTO):Promise<main.PaymentDTO>;

export function CreateProductionJob(arg1:main.ProductionJobInput):Promise<main.ProductionJobDTO>;

export function CreateProof(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<main.ProofDTO>;

export function CreatePurchase(arg1:main.PurchaseInput):Promise<main.PurchaseDTO>;

export function CreateQuote(arg1:main.QuoteInput):Promise<main.QuoteDTO>;

export function CreateService(arg1:main.ServiceInput):Promise<main.ServiceDTO>;

export function CreateSupplier(arg1:main.SupplierInput):Promise<main.SupplierDTO>;

export function CreateTransfer(arg1:main.TransferInputDTO):Promise<main.TransferDTO>;

export function DeleteDraftInvoice(arg1:string):Promise<void>;

export function DeleteDraftPurchase(arg1:string):Promise<void>;

export function DeleteProductionJob(arg1:string):Promise<void>;

export function DeleteSupplier(arg1:string):Promise<void>;

export function GetCustomer(arg1:string):Promise<main.CustomerDTO>;

export function GetCustomerFinancialSummary(arg1:string):Promise<main.CustomerFinancialDTO>;

export function GetInvoice(arg1:string):Promise<main.InvoiceDTO>;

export function GetMachine(arg1:string):Promise<main.MachineDTO>;

export function GetMaterial(arg1:string):Promise<main.MaterialDTO>;

export function GetOrder(arg1:string):Promise<main.OrderDTO>;

export function GetProductionJob(arg1:string):Promise<main.ProductionJobDTO>;

export function GetPurchase(arg1:string):Promise<main.PurchaseDTO>;

export function GetQuote(arg1:string):Promise<main.QuoteDTO>;

export function GetService(arg1:string):Promise<main.ServiceDTO>;

export function GetSupplier(arg1:string):Promise<main.SupplierDTO>;

export function GetSupplierPayableBalance(arg1:string):Promise<number>;

export function ListAccounts():Promise<Array<main.AccountDTO>>;

export function ListAttachments(arg1:string,arg2:string):Promise<Array<main.AttachmentDTO>>;

export function ListCustomers(arg1:boolean):Promise<Array<main.CustomerDTO>>;

export function ListExpenses():Promise<Array<main.ExpenseDTO>>;

export function ListFinancialAccounts():Promise<Array<main.FinancialAccountDTO>>;

export function ListInventoryReservations(arg1:string,arg2:string,arg3:string):Promise<Array<main.InventoryReservationDTO>>;

export function ListInvoices():Promise<Array<main.InvoiceDTO>>;

export function ListJournalEntries():Promise<Array<main.JournalEntryDTO>>;

export function ListMachines(arg1:boolean):Promise<Array<main.MachineDTO>>;

export function ListMaterialMovements(arg1:string):Promise<Array<main.InventoryMovementDTO>>;

export function ListMaterials(arg1:boolean):Promise<Array<main.MaterialDTO>>;

export function ListOrders():Promise<Array<main.OrderDTO>>;

export function ListPayments():Promise<Array<main.PaymentDTO>>;

export function ListProductionConsumptions(arg1:string):Promise<Array<main.ProductionConsumptionDTO>>;

export function ListProductionJobs(arg1:string):Promise<Array<main.ProductionJobDTO>>;

export function ListProofs(arg1:string,arg2:string):Promise<Array<main.ProofDTO>>;

export function ListPurchases():Promise<Array<main.PurchaseDTO>>;

export function ListQuotes():Promise<Array<main.QuoteDTO>>;

export function ListServices(arg1:boolean):Promise<Array<main.ServiceDTO>>;

export function ListSuppliers(arg1:boolean):Promise<Array<main.SupplierDTO>>;

export function ListTransfers():Promise<Array<main.TransferDTO>>;

export function PostInvoice(arg1:string):Promise<main.InvoiceDTO>;

export function PostPurchase(arg1:string):Promise<main.PurchaseDTO>;

export function ReactivateCustomer(arg1:string):Promise<main.CustomerDTO>;

export function ReactivateMachine(arg1:string):Promise<main.MachineDTO>;

export function ReactivateMaterial(arg1:string):Promise<main.MaterialDTO>;

export function ReactivateService(arg1:string):Promise<main.ServiceDTO>;

export function ReactivateSupplier(arg1:string):Promise<main.SupplierDTO>;

export function RecordProductionConsumption(arg1:string,arg2:main.ProductionConsumptionInput):Promise<main.ProductionConsumptionDTO>;

export function ReleaseInventoryReservation(arg1:string):Promise<void>;

export function RemoveAttachment(arg1:string):Promise<void>;

export function RemoveOrderItem(arg1:string,arg2:string):Promise<main.OrderDTO>;

export function RemovePurchaseItem(arg1:string,arg2:string):Promise<main.PurchaseDTO>;

export function RemoveQuoteItem(arg1:string,arg2:string):Promise<main.QuoteDTO>;

export function RemoveServiceCostComponent(arg1:string,arg2:string):Promise<main.ServiceDTO>;

export function RemoveServiceParameter(arg1:string,arg2:string):Promise<main.ServiceDTO>;

export function ReorderOrderItems(arg1:string,arg2:Array<string>):Promise<main.OrderDTO>;

export function ReorderPurchaseItems(arg1:string,arg2:Array<string>):Promise<main.PurchaseDTO>;

export function ReorderQuoteItems(arg1:string,arg2:Array<string>):Promise<main.QuoteDTO>;

export function ReorderServiceCostComponents(arg1:string,arg2:Array<string>):Promise<main.ServiceDTO>;

export function ReorderServiceParameters(arg1:string,arg2:Array<string>):Promise<main.ServiceDTO>;

export function ReplaceOrderItem(arg1:string,arg2:string,arg3:main.OrderItemInput):Promise<main.OrderDTO>;

export function ReplaceQuoteItem(arg1:string,arg2:string,arg3:main.OrderItemInput):Promise<main.QuoteDTO>;

export function ReverseExpense(arg1:string,arg2:string):Promise<main.ExpenseDTO>;

export function ReversePayment(arg1:string,arg2:string):Promise<main.PaymentDTO>;

export function ReverseProductionConsumption(arg1:string,arg2:string):Promise<void>;

export function ReverseTransfer(arg1:string,arg2:string):Promise<main.TransferDTO>;

export function UpdateCustomer(arg1:string,arg2:main.CustomerInput):Promise<main.CustomerDTO>;

export function UpdateInventoryReservation(arg1:string,arg2:string):Promise<main.InventoryReservationDTO>;

export function UpdateMachine(arg1:string,arg2:main.MachineInput):Promise<main.MachineDTO>;

export function UpdateMaterial(arg1:string,arg2:main.MaterialInput):Promise<main.MaterialDTO>;

export function UpdateOrder(arg1:string,arg2:main.OrderInput):Promise<main.OrderDTO>;

export function UpdateOrderCommercialStatus(arg1:string,arg2:string):Promise<main.OrderDTO>;

export function UpdateOrderFulfillmentStatus(arg1:string,arg2:string):Promise<main.OrderDTO>;

export function UpdateProductionJob(arg1:string,arg2:main.ProductionJobInput):Promise<main.ProductionJobDTO>;

export function UpdateProductionJobStatus(arg1:string,arg2:string):Promise<main.ProductionJobDTO>;

export function UpdateProductionOutsourcing(arg1:string,arg2:main.OutsourceInput):Promise<main.ProductionJobDTO>;

export function UpdateProofStatus(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.ProofDTO>;

export function UpdatePurchase(arg1:string,arg2:main.PurchaseInput):Promise<main.PurchaseDTO>;

export function UpdatePurchaseItem(arg1:string,arg2:string,arg3:main.PurchaseItemInput):Promise<main.PurchaseDTO>;

export function UpdateQuote(arg1:string,arg2:main.QuoteInput):Promise<main.QuoteDTO>;

export function UpdateQuoteStatus(arg1:string,arg2:string):Promise<main.QuoteDTO>;

export function UpdateService(arg1:string,arg2:main.ServiceInput):Promise<main.ServiceDTO>;

export function UpdateServiceCostComponent(arg1:string,arg2:string,arg3:main.ServiceCostComponentInput):Promise<main.ServiceDTO>;

export function UpdateServiceParameter(arg1:string,arg2:string,arg3:main.ServiceParameterInput):Promise<main.ServiceDTO>;

export function UpdateSupplier(arg1:string,arg2:main.SupplierInput):Promise<main.SupplierDTO>;

export function VoidInvoice(arg1:string):Promise<main.InvoiceDTO>;
export function CreateCheck(arg1:main.CheckInputDTO):Promise<main.CheckDTO>;
export function GetCheck(arg1:string):Promise<main.CheckDTO>;
export function ListChecks(arg1:string,arg2:string):Promise<Array<main.CheckDTO>>;
export function TransitionCheck(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.CheckDTO>;
export function ListCheckEvents(arg1:string):Promise<Array<main.CheckEventDTO>>;
export function CreateLoan(arg1:main.LoanInputDTO):Promise<main.LoanDTO>;
export function GetLoan(arg1:string):Promise<main.LoanDTO>;
export function ListLoans(arg1:string,arg2:string):Promise<Array<main.LoanDTO>>;
export function ListLoanPayments(arg1:string):Promise<Array<main.LoanPaymentDTO>>;
export function CreateLoanPayment(arg1:main.LoanPaymentInputDTO):Promise<main.LoanPaymentDTO>;
export function ReverseLoanPayment(arg1:string,arg2:string):Promise<main.LoanPaymentDTO>;
export function DeleteDraftCheck(arg1:string):Promise<void>;
export function ListOwners(arg1:boolean):Promise<Array<main.OwnerDTO>>;
export function GetOwner(arg1:string):Promise<main.OwnerDTO>;
export function CreateOwner(arg1:main.OwnerInputDTO):Promise<main.OwnerDTO>;
export function UpdateOwnerShares(arg1:string,arg2:main.OwnerShareInputDTO):Promise<main.OwnerDTO>;
export function ArchiveOwner(arg1:string):Promise<void>;
export function ReactivateOwner(arg1:string):Promise<void>;
export function DeleteOwner(arg1:string):Promise<void>;
export function ListOwnerTransactions(arg1:string):Promise<Array<main.OwnerTransactionDTO>>;
export function CreateOwnerTransaction(arg1:main.OwnerTransactionInputDTO):Promise<main.OwnerTransactionDTO>;
export function ReverseOwnerTransaction(arg1:string,arg2:string):Promise<main.OwnerTransactionDTO>;
export function ListFiscalPeriods():Promise<Array<main.FiscalPeriodDTO>>;
export function GetFiscalPeriod(arg1:string):Promise<main.FiscalPeriodDTO>;
export function PreviewFiscalPeriod(arg1:string):Promise<main.FiscalPeriodDTO>;
export function CreateFiscalPeriod(arg1:main.FiscalPeriodInputDTO):Promise<main.FiscalPeriodDTO>;
export function CloseFiscalPeriod(arg1:string,arg2:string):Promise<main.FiscalPeriodDTO>;
