// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddServiceCostComponent(arg1:string,arg2:main.ServiceCostComponentInput):Promise<main.ServiceDTO>;

export function AddServiceParameter(arg1:string,arg2:main.ServiceParameterInput):Promise<main.ServiceDTO>;

export function ArchiveMachine(arg1:string):Promise<main.MachineDTO>;

export function ArchiveMaterial(arg1:string):Promise<main.MaterialDTO>;

export function ArchiveService(arg1:string):Promise<main.ServiceDTO>;

export function CreateMachine(arg1:main.MachineInput):Promise<main.MachineDTO>;

export function CreateMaterial(arg1:main.MaterialInput):Promise<main.MaterialDTO>;

export function CreateService(arg1:main.ServiceInput):Promise<main.ServiceDTO>;

export function CalculateServicePrice(arg1:main.PricingRequest):Promise<main.PricingDTO>;

export function GetMachine(arg1:string):Promise<main.MachineDTO>;

export function GetMaterial(arg1:string):Promise<main.MaterialDTO>;

export function GetService(arg1:string):Promise<main.ServiceDTO>;

export function ListMachines(arg1:boolean):Promise<Array<main.MachineDTO>>;

export function ListMaterials(arg1:boolean):Promise<Array<main.MaterialDTO>>;

export function ListServices(arg1:boolean):Promise<Array<main.ServiceDTO>>;

export function ReactivateMachine(arg1:string):Promise<main.MachineDTO>;

export function ReactivateMaterial(arg1:string):Promise<main.MaterialDTO>;

export function ReactivateService(arg1:string):Promise<main.ServiceDTO>;

export function RemoveServiceCostComponent(arg1:string,arg2:string):Promise<main.ServiceDTO>;

export function RemoveServiceParameter(arg1:string,arg2:string):Promise<main.ServiceDTO>;

export function ReorderServiceCostComponents(arg1:string,arg2:Array<string>):Promise<main.ServiceDTO>;

export function ReorderServiceParameters(arg1:string,arg2:Array<string>):Promise<main.ServiceDTO>;

export function UpdateMachine(arg1:string,arg2:main.MachineInput):Promise<main.MachineDTO>;

export function UpdateMaterial(arg1:string,arg2:main.MaterialInput):Promise<main.MaterialDTO>;

export function UpdateService(arg1:string,arg2:main.ServiceInput):Promise<main.ServiceDTO>;

export function UpdateServiceCostComponent(arg1:string,arg2:string,arg3:main.ServiceCostComponentInput):Promise<main.ServiceDTO>;

export function UpdateServiceParameter(arg1:string,arg2:string,arg3:main.ServiceParameterInput):Promise<main.ServiceDTO>;
