<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Landmark, Plus, RotateCcw, Trash2, X } from 'lucide-vue-next'
import SectionPanel from '../components/SectionPanel.vue'
import StatusBadge from '../components/StatusBadge.vue'
import WorkspaceStickyStack from '../components/WorkspaceStickyStack.vue'
import JalaliDatePicker from '../components/JalaliDatePicker.vue'
import { checksApi, type CheckEventRecord, type CheckRecord } from '../api/checks'
import { formatMoney, type CurrencyUnit } from '../utils/currency'
import { currentCanonicalDate, formatDateTime } from '../utils/date'

const props = defineProps<{ currencyUnit: CurrencyUnit }>()
const emit = defineEmits<{ notify: [string] }>()
const rows = ref<CheckRecord[]>([]); const selectedId = ref<string|null>(null); const tab = ref('All'); const query = ref(''); const error = ref(''); const history = ref<CheckEventRecord[]>([]); const createMode = ref(false)
const form = ref({direction:'incoming',checkNumber:'',bank:'',branch:'',accountDescriptor:'',payerPayee:'',amountRial:'0',issueDate:currentCanonicalDate(),dueDate:currentCanonicalDate(),customerId:'',supplierId:'',financialAccountId:'',notes:''})
const selected = computed(() => rows.value.find(v=>v.id===selectedId.value) ?? null)
const filtered = computed(() => { const q=query.value.trim().toLowerCase(); return rows.value.filter(v=>{const due=Date.parse(v.dueDate)<Date.now()&&!['Cleared','Returned','Cancelled','Rejected'].includes(v.status); const match=tab.value==='All'||(tab.value==='Incoming'&&v.direction==='incoming')||(tab.value==='Outgoing'&&v.direction==='outgoing')||(tab.value==='Due'&&Date.parse(v.dueDate)>=Date.now()&&!['Cleared','Returned','Cancelled','Rejected'].includes(v.status))||(tab.value==='Overdue'&&due)||(tab.value==='Cleared'&&v.status==='Cleared')||(tab.value==='Closed'&&['Returned','Cancelled','Rejected'].includes(v.status)); return match&&(!q||[v.checkNumber,v.bank,v.payerPayee].join(' ').toLowerCase().includes(q))}) })
const nextStatuses = computed(() => { if(!selected.value)return []; const incoming:{[key:string]:string[]}={Draft:['Received','Cancelled'],Received:['Deposited','Returned','Cancelled'],Deposited:['Cleared','Returned'],Cleared:['Returned'],Returned:['Cancelled']}; const outgoing:{[key:string]:string[]}={Draft:['Issued','Cancelled'],Issued:['Delivered','Returned','Rejected','Cancelled'],Delivered:['Cleared','Returned','Rejected'],Cleared:['Returned','Rejected'],Returned:['Cancelled'],Rejected:['Cancelled']}; return (selected.value.direction==='incoming'?incoming:outgoing)[selected.value.status]??[] })
onMounted(load)
async function load(){try{rows.value=await checksApi.list();if(!selectedId.value&&rows.value[0])select(rows.value[0])}catch(e){error.value=String(e)}}
async function select(v:CheckRecord){selectedId.value=v.id;createMode.value=false;try{history.value=await checksApi.history(v.id)}catch(e){error.value=String(e)}}
function begin(){createMode.value=true;selectedId.value=null;form.value={...form.value,direction:'incoming',checkNumber:'',bank:'',branch:'',accountDescriptor:'',payerPayee:'',amountRial:'0',issueDate:currentCanonicalDate(),dueDate:currentCanonicalDate(),notes:''}}
async function create(){const amount=Number(form.value.amountRial.replaceAll(',',''));if(!form.value.checkNumber||!form.value.bank||!form.value.payerPayee||!amount){error.value='Check number, bank, payer/payee, and a positive amount are required.';return}try{const v=await checksApi.create({...form.value,amountRial:amount});rows.value=[v,...rows.value];await select(v);emit('notify','Check draft created.')}catch(e){error.value=String(e)}}
async function transition(to:string){if(!selected.value)return;try{const v=await checksApi.transition(selected.value.id,to);rows.value=rows.value.map(x=>x.id===v.id?v:x);await select(v);emit('notify',`Check moved to ${to}.`)}catch(e){error.value=String(e)}}
async function removeDraft(){if(!selected.value||selected.value.status!=='Draft')return;try{await checksApi.deleteDraft(selected.value.id);rows.value=rows.value.filter(v=>v.id!==selected.value!.id);selectedId.value=null;history.value=[];emit('notify','Draft check deleted.')}catch(e){error.value=String(e)}}
function tone(s:string){return s==='Cleared'?'green':s==='Returned'||s==='Rejected'||s==='Cancelled'?'red':s==='Deposited'||s==='Delivered'?'blue':'amber'}
function date(v:string){try{return formatDateTime(v)}catch{return '—'}}
</script>
<template><div class="checks-view"><WorkspaceStickyStack><header class="workspace-heading"><div><p class="eyebrow">Finance / instruments</p><h1>Checks</h1><p class="heading-description">Controlled check lifecycles with uncleared instruments kept outside available bank cash.</p></div><button class="button button-primary" @click="begin"><Plus :size="16"/> New check</button></header><section class="orders-filter-bar panel"><input v-model="query" class="workspace-search" type="search" placeholder="Search number, bank, or party"/><div class="workspace-tabs"> <button v-for="value in ['Incoming','Outgoing','Due','Overdue','Cleared','Closed','All']" :key="value" :class="{'is-active':tab===value}" @click="tab=value">{{ value }}</button></div><span class="filter-result">{{ filtered.length }} shown</span></section></WorkspaceStickyStack>
<div v-if="error" class="form-error" role="alert">{{ error }} <button class="icon-button" @click="error=''" aria-label="Dismiss"><X :size="14"/></button></div>
<section class="checks-layout"><SectionPanel title="Check register" subtitle="Only valid next lifecycle actions are offered."><div v-if="filtered.length" class="table-wrap"><table class="data-table"><thead><tr><th>Check</th><th>Direction</th><th>Party</th><th>Due</th><th>Amount</th><th>Status</th></tr></thead><tbody><tr v-for="v in filtered" :key="v.id" :class="{'is-selected':selectedId===v.id}" @click="select(v)"><td><span class="table-primary">{{ v.checkNumber }}</span><span class="table-secondary">{{ v.bank }}</span></td><td>{{ v.direction==='incoming'?'Incoming':'Outgoing' }}</td><td>{{ v.payerPayee }}</td><td>{{ date(v.dueDate) }}</td><td>{{ formatMoney(v.amountRial,props.currencyUnit) }}</td><td><StatusBadge :label="v.status" :tone="tone(v.status)"/></td></tr></tbody></table></div><div v-else class="workspace-state"><Landmark :size="22"/><p>No checks in this view.</p></div></SectionPanel>
<SectionPanel v-if="createMode" title="New check" subtitle="Drafts have no financial effect until lifecycle posting."><form class="check-form" @submit.prevent="create"><div class="check-form-grid"><label class="form-field"><span>Direction</span><select v-model="form.direction"><option value="incoming">Incoming</option><option value="outgoing">Outgoing</option></select></label><label class="form-field"><span>Check number</span><input v-model="form.checkNumber" required/></label><label class="form-field"><span>Bank</span><input v-model="form.bank" required/></label><label class="form-field"><span>Payer / payee</span><input v-model="form.payerPayee" required/></label><label class="form-field"><span>Amount (Rial)</span><input v-model="form.amountRial" inputmode="numeric" required/></label><label class="form-field"><span>Branch</span><input v-model="form.branch"/></label><label class="form-field"><span>Issue date</span><JalaliDatePicker v-model="form.issueDate"/></label><label class="form-field"><span>Due date</span><JalaliDatePicker v-model="form.dueDate"/></label></div><label class="form-field"><span>Notes</span><textarea v-model="form.notes" rows="3"/></label><div class="inspector-actions"><button class="button button-secondary" type="button" @click="createMode=false">Cancel</button><button class="button button-primary"><Plus :size="15"/> Save draft</button></div></form></SectionPanel>
<SectionPanel v-else-if="selected" title="Check inspector" :subtitle="`${selected.checkNumber} · ${selected.payerPayee}`"><div class="check-inspector"><div class="inspector-heading"><div class="material-inspector-icon"><Landmark :size="19"/></div><div><h3>{{ selected.bank }}</h3><p>{{ selected.direction==='incoming'?'Incoming':'Outgoing' }} · due {{ date(selected.dueDate) }}</p></div></div><StatusBadge :label="selected.status" :tone="tone(selected.status)"/><dl class="purchase-totals"><div><dt>Amount</dt><dd>{{ formatMoney(selected.amountRial,props.currencyUnit) }}</dd></div><div><dt>Account</dt><dd>{{ selected.financialAccountId||'Default bank' }}</dd></div></dl><div class="inspector-actions"><button v-for="value in nextStatuses" :key="value" class="button" :class="value==='Cancelled'?'button-danger':'button-secondary'" @click="transition(value)"><RotateCcw :size="14"/> {{ value }}</button></div><div class="check-history"><h3>Lifecycle history</h3><div v-for="event in history" :key="event.id" class="accounting-row"><span><strong>{{ event.fromStatus }} → {{ event.toStatus }}</strong><small>{{ date(event.occurredAt) }}<template v-if="event.note"> · {{ event.note }}</template></small></span><small>{{ event.journalEntryId?'Journaled':'State only' }}</small></div><div v-if="!history.length" class="workspace-state">No lifecycle events yet.</div></div></div></SectionPanel><SectionPanel v-else title="Check inspector" subtitle="Select a check to inspect lifecycle and history."><div class="workspace-state">No check selected.</div></SectionPanel></section></div></template>
<style scoped>.checks-view{display:grid;gap:16px;min-width:0}.checks-layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(320px,460px);gap:16px;align-items:start}.workspace-search{min-width:160px;flex:1}.workspace-tabs{display:flex;gap:4px;overflow:auto}.workspace-tabs button{border:0;background:transparent;padding:7px 9px;color:var(--text-muted);white-space:nowrap;border-radius:7px;cursor:pointer}.workspace-tabs button.is-active{background:var(--surface-muted);color:var(--text)}.check-form,.check-inspector{display:grid;gap:14px;min-width:0}.check-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.check-history{border-top:1px solid var(--border);padding-top:14px;display:grid;gap:9px}.check-history h3{margin:0;font-size:13px}@media(max-width:1050px){.checks-layout{grid-template-columns:1fr}}@media(max-width:650px){.check-form-grid{grid-template-columns:1fr}}
</style>
