<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Landmark, Plus, RotateCcw, Trash2, X } from 'lucide-vue-next'
import SectionPanel from '../components/SectionPanel.vue'
import StatusBadge from '../components/StatusBadge.vue'
import WorkspaceStickyStack from '../components/WorkspaceStickyStack.vue'
import JalaliDatePicker from '../components/JalaliDatePicker.vue'
import { checksApi, type CheckEventRecord, type CheckRecord } from '../api/checks'
import { formatMoney, type CurrencyUnit } from '../utils/currency'
import { currentCanonicalDate, formatDateTime } from '../utils/date'
import { normalizeError } from '../ui/feedback'
import SearchField from '../components/SearchField.vue'
import SelectField from '../components/SelectField.vue'

const props = defineProps<{ currencyUnit: CurrencyUnit }>()
const emit = defineEmits<{ notify: [string] }>()
const rows = ref<CheckRecord[]>([]); const selectedId = ref<string|null>(null); const tab = ref('All'); const query = ref(''); const error = ref(''); const history = ref<CheckEventRecord[]>([]); const createMode = ref(false)
const form = ref({direction:'incoming',checkNumber:'',bank:'',branch:'',accountDescriptor:'',payerPayee:'',amountRial:'0',issueDate:currentCanonicalDate(),dueDate:currentCanonicalDate(),customerId:'',supplierId:'',financialAccountId:'',notes:''})
const selected = computed(() => rows.value.find(v=>v.id===selectedId.value) ?? null)
const filtered = computed(() => { const q=query.value.trim().toLowerCase(); return rows.value.filter(v=>{const due=Date.parse(v.dueDate)<Date.now()&&!['Cleared','Returned','Cancelled','Rejected'].includes(v.status); const match=tab.value==='All'||(tab.value==='Incoming'&&v.direction==='incoming')||(tab.value==='Outgoing'&&v.direction==='outgoing')||(tab.value==='Due'&&Date.parse(v.dueDate)>=Date.now()&&!['Cleared','Returned','Cancelled','Rejected'].includes(v.status))||(tab.value==='Overdue'&&due)||(tab.value==='Cleared'&&v.status==='Cleared')||(tab.value==='Closed'&&['Returned','Cancelled','Rejected'].includes(v.status)); return match&&(!q||[v.checkNumber,v.bank,v.payerPayee].join(' ').toLowerCase().includes(q))}) })
const nextStatuses = computed(() => { if(!selected.value)return []; const incoming:{[key:string]:string[]}={Draft:['Received','Cancelled'],Received:['Deposited','Returned','Cancelled'],Deposited:['Cleared','Returned'],Cleared:['Returned'],Returned:['Cancelled']}; const outgoing:{[key:string]:string[]}={Draft:['Issued','Cancelled'],Issued:['Delivered','Returned','Rejected','Cancelled'],Delivered:['Cleared','Returned','Rejected'],Cleared:['Returned','Rejected'],Returned:['Cancelled'],Rejected:['Cancelled']}; return (selected.value.direction==='incoming'?incoming:outgoing)[selected.value.status]??[] })
onMounted(load)
async function load(){try{rows.value=await checksApi.list();if(!selectedId.value&&rows.value[0])select(rows.value[0])}catch(e){error.value=normalizeError(e).message}}
async function select(v:CheckRecord){selectedId.value=v.id;createMode.value=false;try{history.value=await checksApi.history(v.id)}catch(e){error.value=normalizeError(e).message}}
function begin(){createMode.value=true;selectedId.value=null;form.value={...form.value,direction:'incoming',checkNumber:'',bank:'',branch:'',accountDescriptor:'',payerPayee:'',amountRial:'0',issueDate:currentCanonicalDate(),dueDate:currentCanonicalDate(),notes:''}}
async function create(){const amount=Number(form.value.amountRial.replaceAll(',',''));if(!form.value.checkNumber||!form.value.bank||!form.value.payerPayee||!amount){error.value='Check number, bank, payer/payee, and a positive amount are required.';return}try{const v=await checksApi.create({...form.value,amountRial:amount});rows.value=[v,...rows.value];await select(v);emit('notify','Check draft created.')}catch(e){error.value=normalizeError(e).message}}
async function transition(to:string){if(!selected.value)return;try{const v=await checksApi.transition(selected.value.id,to);rows.value=rows.value.map(x=>x.id===v.id?v:x);await select(v);emit('notify',`Check moved to ${to}.`)}catch(e){error.value=normalizeError(e).message}}
async function removeDraft(){if(!selected.value||selected.value.status!=='Draft')return;try{await checksApi.deleteDraft(selected.value.id);rows.value=rows.value.filter(v=>v.id!==selected.value!.id);selectedId.value=null;history.value=[];emit('notify','Draft check deleted.')}catch(e){error.value=normalizeError(e).message}}
function tone(s:string){return s==='Cleared'?'green':s==='Returned'||s==='Rejected'||s==='Cancelled'?'red':s==='Deposited'||s==='Delivered'?'blue':'amber'}
function date(v:string){try{return formatDateTime(v)}catch{return '—'}}
</script>
<template><div><WorkspaceStickyStack><header><div><p>Finance / instruments</p><h1>Checks</h1><p>Controlled check lifecycles with uncleared instruments kept outside available bank cash.</p></div><button class="btn btn-ghost" @click="begin"><Plus :size="16"/> New check</button></header><section><SearchField v-model="query" label="Search checks" placeholder="Search number, bank, or party" /><div> <button class="btn btn-sm" v-for="value in ['Incoming','Outgoing','Due','Overdue','Cleared','Closed','All']" :key="value" :class="tab===value ? 'btn-primary' : 'btn-ghost'" @click="tab=value">{{ value }}</button></div><span>{{ filtered.length }} shown</span></section></WorkspaceStickyStack>
<div v-if="error" role="alert">{{ error }} <button class="btn btn-ghost" @click="error=''" aria-label="Dismiss"><X :size="14"/></button></div>
<section><SectionPanel title="Check register" subtitle="Only valid next lifecycle actions are offered."><div v-if="filtered.length"><table class="table table-zebra w-full"><thead><tr><th>Check</th><th>Direction</th><th>Party</th><th>Due</th><th>Amount</th><th>Status</th></tr></thead><tbody><tr v-for="v in filtered" :key="v.id" :class="{'bg-base-300':selectedId===v.id}" @click="select(v)"><td><span>{{ v.checkNumber }}</span><span>{{ v.bank }}</span></td><td>{{ v.direction==='incoming'?'Incoming':'Outgoing' }}</td><td>{{ v.payerPayee }}</td><td>{{ date(v.dueDate) }}</td><td>{{ formatMoney(v.amountRial,props.currencyUnit) }}</td><td><StatusBadge :label="v.status" :tone="tone(v.status)"/></td></tr></tbody></table></div><div v-else><Landmark :size="22"/><p>No checks in this view.</p></div></SectionPanel>
<SectionPanel v-if="createMode" title="New check" subtitle="Drafts have no financial effect until lifecycle posting."><form @submit.prevent="create"><div><label class="form-control gap-1"><span>Direction</span><SelectField v-model="form.direction" label="Direction" :options="[{ label: 'Incoming', value: 'incoming' }, { label: 'Outgoing', value: 'outgoing' }]" /></label><label class="form-control gap-1"><span>Check number</span><input class="input input-bordered w-full min-w-0" v-model="form.checkNumber" required/></label><label class="form-control gap-1"><span>Bank</span><input class="input input-bordered w-full min-w-0" v-model="form.bank" required/></label><label class="form-control gap-1"><span>Payer / payee</span><input class="input input-bordered w-full min-w-0" v-model="form.payerPayee" required/></label><label class="form-control gap-1"><span>Amount (Rial)</span><input class="input input-bordered w-full min-w-0" v-model="form.amountRial" inputmode="numeric" required/></label><label class="form-control gap-1"><span>Branch</span><input class="input input-bordered w-full min-w-0" v-model="form.branch"/></label><label class="form-control gap-1"><span>Issue date</span><JalaliDatePicker v-model="form.issueDate"/></label><label class="form-control gap-1"><span>Due date</span><JalaliDatePicker v-model="form.dueDate"/></label></div><label class="form-control gap-1"><span>Notes</span><textarea class="textarea textarea-bordered w-full min-w-0" v-model="form.notes" rows="3"/></label><div><button class="btn btn-ghost" type="button" @click="createMode=false">Cancel</button><button class="btn btn-ghost"><Plus :size="15"/> Save draft</button></div></form></SectionPanel>
<SectionPanel v-else-if="selected" title="Check inspector" :subtitle="`${selected.checkNumber} · ${selected.payerPayee}`"><div><div><div><Landmark :size="19"/></div><div><h3>{{ selected.bank }}</h3><p>{{ selected.direction==='incoming'?'Incoming':'Outgoing' }} · due {{ date(selected.dueDate) }}</p></div></div><StatusBadge :label="selected.status" :tone="tone(selected.status)"/><dl><div><dt>Amount</dt><dd>{{ formatMoney(selected.amountRial,props.currencyUnit) }}</dd></div><div><dt>Account</dt><dd>{{ selected.financialAccountId||'Default bank' }}</dd></div></dl><div><button v-for="value in nextStatuses" :key="value" :class="value==='Cancelled'?'btn-error':'btn-outline'" @click="transition(value)"><RotateCcw :size="14"/> {{ value }}</button></div><div><h3>Lifecycle history</h3><div v-for="event in history" :key="event.id"><span><strong>{{ event.fromStatus }} → {{ event.toStatus }}</strong><small>{{ date(event.occurredAt) }}<template v-if="event.note"> · {{ event.note }}</template></small></span><small>{{ event.journalEntryId?'Journaled':'State only' }}</small></div><div v-if="!history.length">No lifecycle events yet.</div></div></div></SectionPanel><SectionPanel v-else title="Check inspector" subtitle="Select a check to inspect lifecycle and history."><div>No check selected.</div></SectionPanel></section></div></template>
