<script setup lang="ts">
import { onMounted, ref } from 'vue'
import SectionPanel from '../components/SectionPanel.vue'
import StatusBadge from '../components/StatusBadge.vue'
import type { CurrencyUnit } from '../utils/currency'
import { formatMoney, formatMoneyInput, parseMoneyInput } from '../utils/currency'
import { formatDateTime } from '../utils/date'
import { accountingApi, type FinancialAccountRecord, type PaymentRecord } from '../api/accounting'
import { ordersApi } from '../api/orders'
const props=defineProps<{order:any;currencyUnit:CurrencyUnit}>();const emit=defineEmits<{notify:[message:string];saved:[order:any]}>();const financial=ref<FinancialAccountRecord[]>([]);const payments=ref<PaymentRecord[]>([]);const amount=ref('');const account=ref('FIN-CASH');const method=ref('cash');const loading=ref(false)
const money=(n:number)=>formatMoney(n,props.currencyUnit)
async function load(){loading.value=true;try{financial.value=await accountingApi.financialAccounts();payments.value=(await accountingApi.payments()).filter(p=>p.allocations.some(a=>a.targetType==='order'&&a.targetId===props.order.id))}catch(e){emit('notify',String(e))}finally{loading.value=false}}
async function refreshOrder(){emit('saved',await ordersApi.get(props.order.id))}
async function post(){try{const n=parseMoneyInput(amount.value,props.currencyUnit);if(n===null||n<=0)throw new Error('Enter a positive amount');await accountingApi.createPayment({direction:'incoming',method:method.value,financialAccountId:account.value,customerId:props.order.customerId,amountRial:n,allocations:[{targetType:'order',targetId:props.order.id,amountRial:n}]});amount.value='';await load();await refreshOrder();emit('notify','Order payment posted')}catch(e){emit('notify',String(e))}}
async function reverse(p:PaymentRecord){try{await accountingApi.reversePayment(p.id);await load();await refreshOrder();emit('notify','Payment reversed')}catch(e){emit('notify',String(e))}}
onMounted(load)
</script>
<template><div class="order-payments-grid"><SectionPanel title="Payment status" subtitle="Paid and remaining amounts are derived by the backend."><div class="payment-summary"><span>Total<strong>{{ money(order.totalRial) }}</strong></span><span>Paid<strong>{{ money(order.paidRial||0) }}</strong></span><span>Remaining<strong>{{ money(order.remainingRial??order.totalRial) }}</strong></span></div><form class="order-payment-form" @submit.prevent="post"><select v-model="account"><option v-for="a in financial" :key="a.id" :value="a.id">{{ a.name }}</option></select><select v-model="method"><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="check">Check</option></select><input v-model="amount" :placeholder="`Amount (${props.currencyUnit})`" inputmode="numeric" @blur="amount=formatMoneyInput(parseMoneyInput(amount,props.currencyUnit)||0,props.currencyUnit)"/><button class="button button-primary" type="submit">Post payment</button></form></SectionPanel><SectionPanel title="Order payment history" subtitle="Reversals preserve the original payment and journal entry."><div v-if="!payments.length" class="workspace-state">No allocated payments for this order.</div><div v-for="p in payments" :key="p.id" class="order-payment-row"><span><strong>{{ p.paymentNumber }}</strong><small>{{ money(p.amountRial) }} · {{ formatDateTime(p.postedAt) }}</small></span><span><StatusBadge :label="p.status" :tone="p.status==='posted'?'green':'slate'"/><button v-if="p.status==='posted'" class="text-button" @click="reverse(p)">Reverse</button></span></div></SectionPanel></div></template>
<style scoped>.order-payments-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:16px}.payment-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-bottom:16px}.payment-summary span{display:grid;gap:5px;background:var(--surface-muted);padding:12px;border-radius:8px;font-size:12px;color:var(--text-muted)}.payment-summary strong{color:var(--text);font-size:15px}.order-payment-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.order-payment-form input,.order-payment-form select{min-width:0;width:100%;box-sizing:border-box}.order-payment-form input{grid-column:1/-1}.order-payment-row{display:flex;justify-content:space-between;gap:10px;padding:11px 0;border-bottom:1px solid var(--border)}.order-payment-row span{display:flex;gap:8px;align-items:center}.order-payment-row span:first-child{display:grid;gap:3px}.order-payment-row small{color:var(--text-muted)}@media(max-width:850px){.order-payments-grid{grid-template-columns:1fr}}@media(max-width:500px){.payment-summary{grid-template-columns:1fr}.order-payment-form{grid-template-columns:1fr}.order-payment-form input{grid-column:auto}}</style>
