<script setup lang="ts">
import { computed, ref } from 'vue'
import { ChevronDown, Plus, Search, SearchX } from 'lucide-vue-next'
import StatusBadge from '../components/StatusBadge.vue'
import WorkspaceStickyStack from '../components/WorkspaceStickyStack.vue'
import type { OrderRecord } from '../api/orders'
import { formatMoney, type CurrencyUnit } from '../utils/currency'
import { formatDateTime } from '../utils/date'
type Tone='blue'|'green'|'amber'|'red'|'slate'
const props=defineProps<{orders:OrderRecord[];currencyUnit:CurrencyUnit;loading?:boolean;error?:string}>()
const emit=defineEmits<{ 'open-order':[id:string];'new-order':[] }>()
const query=ref('');const commercial=ref('All');const fulfillment=ref('All');const payment=ref('All');const priority=ref('All');const selected=ref<string|null>(null)
const filtered=computed(()=>props.orders.filter(o=>{const q=query.value.trim().toLowerCase();return(!q||[o.orderNumber,o.customerName,...o.items.map(i=>i.serviceName)].some(v=>v.toLowerCase().includes(q)))&&(commercial.value==='All'||o.commercialStatus===commercial.value)&&(fulfillment.value==='All'||o.fulfillmentStatus===fulfillment.value)&&(payment.value==='All'||o.paymentStatus===payment.value)&&(priority.value==='All'||o.priority===priority.value)}))
function money(v:number){return formatMoney(v,props.currencyUnit)}
function tone(v:string):Tone{return v==='Confirmed'||v==='In Production'?'blue':v==='Closed'||v==='Delivered'||v==='Paid'||v==='Ready'?'green':v==='Cancelled'?'red':v==='Partially Paid'?'amber':'slate'}
function itemSummary(o:OrderRecord){return o.items.map(i=>i.serviceName).join(' · ')||'No configured items'}
function clear(){query.value='';commercial.value=fulfillment.value=payment.value=priority.value='All'}
</script>
<template><div>
  <WorkspaceStickyStack><header><div><p>Sales / operational queue</p><h1>Orders</h1><p>Track persisted customer orders and their independent state axes.</p></div><button class="btn btn-ghost" type="button" @click="emit('new-order')"><Plus :size="16" :stroke-width="1.8" aria-hidden="true"/>New order</button></header>
    <section aria-label="Order filters"><label class="form-control gap-1"><span>Search orders</span><Search :size="16" aria-hidden="true"/><input class="input input-bordered w-full min-w-0" v-model="query" type="search" placeholder="Search order, customer, or service"/></label><label class="form-control gap-1"><span>Commercial</span><span><select class="select select-bordered w-full min-w-0" v-model="commercial"><option>All</option><option>Draft</option><option>Confirmed</option><option>Closed</option><option>Cancelled</option></select><ChevronDown :size="14"/></span></label><label class="form-control gap-1"><span>Fulfillment</span><span><select class="select select-bordered w-full min-w-0" v-model="fulfillment"><option>All</option><option>Pending</option><option>In Production</option><option>Ready</option><option>Delivered</option></select><ChevronDown :size="14"/></span></label><label class="form-control gap-1"><span>Payment</span><span><select class="select select-bordered w-full min-w-0" v-model="payment"><option>All</option><option>Unpaid</option><option>Partially Paid</option><option>Paid</option></select><ChevronDown :size="14"/></span></label><label class="form-control gap-1"><span>Priority</span><span><select class="select select-bordered w-full min-w-0" v-model="priority"><option>All</option><option>Urgent</option><option>High</option><option>Normal</option><option>Low</option></select><ChevronDown :size="14"/></span></label><button class="btn btn-ghost" v-if="query||commercial!=='All'||fulfillment!=='All'||payment!=='All'||priority!=='All'" @click="clear">Clear</button><span>{{ filtered.length }} of {{ props.orders.length }} orders</span></section>
  </WorkspaceStickyStack>
  <section><header><div><h2>All orders</h2><p>Open an order to inspect its accepted pricing snapshots.</p></div><span><span/>Independent state axes</span></header>
    <div v-if="loading">Loading orders…</div><div v-else-if="error">{{ error }}</div><div v-else-if="!filtered.length"><SearchX :size="22" aria-hidden="true"/><strong>{{ props.orders.length?'No orders match these filters':'No persisted orders yet' }}</strong><button class="btn btn-ghost" v-if="props.orders.length" @click="clear">Clear filters</button></div>
    <div v-else><table class="table table-zebra w-full"><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Created</th><th>Promised</th><th>Total</th><th>Commercial</th><th>Fulfillment</th><th>Payment</th><th>Priority</th></tr></thead><tbody><tr v-for="order in filtered" :key="order.id" :class="{'bg-base-300':selected===order.id}" tabindex="0" @click="selected=order.id" @dblclick="emit('open-order',order.id)" @keydown.enter="emit('open-order',order.id)"><td><button class="btn btn-ghost" @click.stop="emit('open-order',order.id)">{{ order.orderNumber }}</button></td><td><span>{{ order.customerName||'Walk-in customer' }}</span><span>{{ order.customerPhone||'No contact details' }}</span></td><td><span>{{ itemSummary(order) }}</span><span>{{ order.items.length }} line items</span></td><td>{{ formatDateTime(order.createdAt) }}</td><td>{{ order.promisedAt?formatDateTime(order.promisedAt):'—' }}</td><td>{{ money(order.totalRial) }}</td><td><StatusBadge :label="order.commercialStatus" :tone="tone(order.commercialStatus)"/></td><td><StatusBadge :label="order.fulfillmentStatus" :tone="tone(order.fulfillmentStatus)"/></td><td><StatusBadge :label="order.paymentStatus" :tone="tone(order.paymentStatus)"/></td><td><StatusBadge :label="order.priority" :tone="tone(order.priority)"/></td></tr></tbody></table></div>
  </section>
</div></template>
