<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { ArrowLeft, ChevronDown, Pencil, Plus, Trash2, ArrowUp, ArrowDown } from 'lucide-vue-next'
import WorkspaceStickyStack from '../components/WorkspaceStickyStack.vue'
import WorkspaceTabs from '../components/WorkspaceTabs.vue'
import StatusBadge from '../components/StatusBadge.vue'
import JalaliDatePicker from '../components/JalaliDatePicker.vue'
import OrderItemConfigurator from '../components/OrderItemConfigurator.vue'
import DocumentMetadataPanel from '../components/DocumentMetadataPanel.vue'
import type { OrderRecord, OrderPayload, OrderItemPayload } from '../api/orders'
import { ordersApi } from '../api/orders'
import type { CurrencyUnit } from '../utils/currency'
import { formatMoney, formatMoneyInput, parseMoneyInput } from '../utils/currency'
import { formatDateTime } from '../utils/date'
import OrderProductionPanel from './OrderProductionPanel.vue'
import OrderPaymentsPanel from './OrderPaymentsPanel.vue'
import OrderInvoicePanel from './OrderInvoicePanel.vue'
const props=defineProps<{order:OrderRecord;currencyUnit:CurrencyUnit;customers:any[];services:any[];materials:any[]}>();const emit=defineEmits<{back:[];notify:[message:string];saved:[order:OrderRecord]}>()
const tab=ref('Overview');const customerId=ref('');const promisedAt=ref<string|null>(null);const priority=ref('Normal');const notes=ref('');const discountText=ref('');const editorOpen=ref(false);const editingItem=ref<any|null>(null);const saving=ref(false)
const tabs=['Overview','Items','Production','Payments','Invoices','Files','History'];const customer=computed(()=>props.customers.find(c=>c.id===customerId.value));
watch(()=>props.order,(o)=>{customerId.value=o.customerId||'';promisedAt.value=o.promisedAt;priority.value=o.priority;notes.value=o.notes;discountText.value=formatMoneyInput(o.discountRial,props.currencyUnit)},{immediate:true})
function tone(v:string){return v==='Confirmed'||v==='In Production'?'blue':v==='Closed'||v==='Delivered'||v==='Paid'||v==='Ready'?'green':v==='Cancelled'?'red':v==='Partially Paid'?'amber':'slate'}
function money(v:number){return formatMoney(v,props.currencyUnit)}
function payload():OrderPayload{return{customerId:customerId.value,promisedAt:promisedAt.value,priority:priority.value,notes:notes.value,discountRial:parseMoneyInput(discountText.value,props.currencyUnit)||0}}
async function saveMetadata(){saving.value=true;try{const result=await ordersApi.update(props.order.id,payload());emit('saved',result);emit('notify','Order details saved')}catch(e){emit('notify',String(e))}finally{saving.value=false}}
async function updateDiscount(){saving.value=true;try{const amount=parseMoneyInput(discountText.value,props.currencyUnit);if(amount===null)throw new Error('Enter a valid discount');const result=await ordersApi.discount(props.order.id,amount);emit('saved',result);emit('notify','Discount applied')}catch(e){emit('notify',String(e))}finally{saving.value=false}}
async function configured(input:OrderItemPayload){saving.value=true;const replacing=Boolean(editingItem.value);try{const result=replacing?await ordersApi.replaceItem(props.order.id,editingItem.value.id,input):await ordersApi.addItem(props.order.id,input);emit('saved',result);editorOpen.value=false;editingItem.value=null;emit('notify',replacing?'Item replaced':'Item added')}catch(e){emit('notify',String(e))}finally{saving.value=false}}
async function remove(item:any){try{emit('saved',await ordersApi.removeItem(props.order.id,item.id));emit('notify','Item removed')}catch(e){emit('notify',String(e))}}
async function move(item:any,delta:number){const items=[...props.order.items].sort((a,b)=>a.position-b.position);const index=items.findIndex(i=>i.id===item.id);const next=index+delta;if(next<0||next>=items.length)return;[items[index],items[next]]=[items[next],items[index]];try{emit('saved',await ordersApi.reorderItems(props.order.id,items.map(i=>i.id)))}catch(e){emit('notify',String(e))}}
async function changeCommercial(e:Event){try{emit('saved',await ordersApi.commercialStatus(props.order.id,(e.target as HTMLSelectElement).value));emit('notify','Commercial status updated')}catch(err){emit('notify',String(err))}}
async function changeFulfillment(e:Event){try{emit('saved',await ordersApi.fulfillmentStatus(props.order.id,(e.target as HTMLSelectElement).value));emit('notify','Fulfillment status updated')}catch(err){emit('notify',String(err))}}
function snapshot(item:any,key:string){try{return JSON.parse(item[key]||'[]')}catch{return[]}}
</script>
<template><div><WorkspaceStickyStack :flush="true"><header><button class="btn btn-ghost" @click="emit('back')"><ArrowLeft :size="16"/>Orders</button><div><p>Sales / Order workspace</p><div><h1>{{ order.orderNumber }}</h1><StatusBadge :label="order.commercialStatus" :tone="tone(order.commercialStatus)"/></div><p>{{ order.customerName||'Walk-in customer' }} · {{ order.items.length }} line items</p></div><div><span><select class="select select-bordered w-full min-w-0" :value="order.commercialStatus" aria-label="Commercial status" @change="changeCommercial"><option>Draft</option><option>Confirmed</option><option>Closed</option><option>Cancelled</option></select><ChevronDown :size="14"/></span><button class="btn btn-ghost" :disabled="saving" @click="saveMetadata">{{ saving?'Saving…':'Save order' }}</button></div></header><section><div><span>Customer</span><span>{{ order.customerName||'Walk-in customer' }}</span><span>{{ customer?.phone||order.customerPhone||'No contact details' }}</span></div><div><span>Created</span><span>{{ formatDateTime(order.createdAt) }}</span><span>Jalali presentation</span></div><div><span>Promised date</span><JalaliDatePicker v-model="promisedAt" placeholder="Set promised date"/></div><div><span>Priority</span><span><select class="select select-bordered w-full min-w-0" v-model="priority" aria-label="Priority"><option>Urgent</option><option>High</option><option>Normal</option><option>Low</option></select><ChevronDown :size="14"/></span></div><div><span>Order states</span><div><StatusBadge :label="order.commercialStatus" :tone="tone(order.commercialStatus)"/><span><select class="select select-bordered w-full min-w-0" :value="order.fulfillmentStatus" aria-label="Fulfillment status" @change="changeFulfillment"><option>Pending</option><option>In Production</option><option>Ready</option><option>Delivered</option></select><ChevronDown :size="14"/></span><StatusBadge :label="order.paymentStatus" :tone="tone(order.paymentStatus)"/></div></div></section><WorkspaceTabs :tabs="tabs" :active-tab="tab" @update:active-tab="tab=$event"/></WorkspaceStickyStack>
<section v-if="tab==='Overview'"><section><header><div><h2>Order details</h2><p>Customer and delivery context</p></div></header><div><label class="form-control gap-1">Customer<span><select class="select select-bordered w-full min-w-0" v-model="customerId"><option value="">Walk-in customer</option><option v-for="c in customers.filter((x:any)=>x.active||x.id===customerId)" :key="c.id" :value="c.id">{{ c.name }}</option></select><ChevronDown :size="14"/></span></label><label class="form-control gap-1">Notes<textarea class="textarea textarea-bordered w-full min-w-0" v-model="notes" rows="5" placeholder="Order notes"/></label></div><button class="btn btn-ghost" :disabled="saving" @click="saveMetadata">Save details</button></section><section><header><h2>Order summary</h2></header><div><span>Subtotal<strong>{{ money(order.subtotalRial) }}</strong></span><span>Discount<strong>{{ money(order.discountRial) }}</strong></span><span>Total<strong>{{ money(order.totalRial) }}</strong></span><span>Estimated cost<strong>{{ money(order.estimatedCostRial) }}</strong></span></div><label class="form-control gap-1">Order discount<input class="input input-bordered w-full min-w-0" :value="discountText" inputmode="decimal" @input="discountText=($event.target as HTMLInputElement).value" @blur="discountText=formatMoneyInput(parseMoneyInput(discountText,props.currencyUnit)||0,props.currencyUnit)"/><button class="btn btn-ghost" @click="updateDiscount">Apply</button></label></section></section>
<section v-else-if="tab==='Items'"><div v-if="!editorOpen"><header><div><h2>Configured items</h2><p>Each item keeps its accepted service and pricing snapshot.</p></div><button class="btn btn-ghost" @click="editorOpen=true"><Plus :size="15"/>Add service item</button></header><div v-if="!order.items.length">No items yet. Add the first configured service.</div><div v-for="item in [...order.items].sort((a,b)=>a.position-b.position)" :key="item.id"><div>{{ item.position+1 }}</div><div><strong>{{ item.serviceName }}</strong><span>{{ item.quantity }} {{ item.quantityUnit }}<template v-if="item.notes"> · {{ item.notes }}</template></span><small>Accepted snapshot · {{ snapshot(item,'resolvedParametersJson').length }} parameters · {{ snapshot(item,'costBreakdownJson').length }} cost lines</small></div><div><span>Cost {{ money(item.estimatedCostRial) }}</span><strong>{{ money(item.sellingPriceRial) }}</strong></div><div><button class="btn btn-ghost" aria-label="Move item up" @click="move(item,-1)"><ArrowUp :size="14"/></button><button class="btn btn-ghost" aria-label="Move item down" @click="move(item,1)"><ArrowDown :size="14"/></button><button class="btn btn-ghost" aria-label="Reconfigure item" @click="editingItem=item;editorOpen=true"><Pencil :size="14"/></button><button class="btn btn-ghost" aria-label="Remove item" @click="remove(item)"><Trash2 :size="14"/></button></div></div></div><OrderItemConfigurator v-else :services="services" :materials="materials" :currency-unit="currencyUnit" :initial="editingItem" @configured="configured" @cancel="editorOpen=false;editingItem=null"/></section>
<OrderInvoicePanel v-else-if="tab==='Invoices'" :order="order" :currency-unit="currencyUnit" @notify="emit('notify',$event)" @saved="emit('saved',$event)" /><DocumentMetadataPanel v-else-if="tab==='Files'" owner-type="order" :owner-id="order.id" :protected-context="order.commercialStatus !== 'Draft'" @notify="emit('notify',$event)" /><OrderProductionPanel v-else-if="tab==='Production'" :order="order" :currency-unit="currencyUnit" /><OrderPaymentsPanel v-else-if="tab==='Payments'" :order="order" :currency-unit="currencyUnit" @notify="emit('notify',$event)" @saved="emit('saved',$event)" /><section v-else><strong>{{ tab }}</strong><span>This workflow is intentionally reserved for a later milestone. Persisted order data remains unchanged.</span></section>
</div></template>
