<script setup lang="ts">
import { computed, ref } from 'vue'
import { ChevronDown, Plus, Search, SearchX } from 'lucide-vue-next'
import StatusBadge from '../components/StatusBadge.vue'
import WorkspaceStickyStack from '../components/WorkspaceStickyStack.vue'
import type { OrderRecord } from '../api/orders'
import { formatMoney, type CurrencyUnit } from '../utils/currency'
import { formatDateTime } from '../utils/date'
type Tone='blue'|'green'|'amber'|'red'|'slate'
const props=defineProps<{orders:OrderRecord[];currencyUnit:CurrencyUnit;loading?:boolean;error?:string}>()
const emit=defineEmits<{ 'open-order':[id:string];'new-order':[] }>()
const query=ref('');const commercial=ref('All');const fulfillment=ref('All');const payment=ref('All');const priority=ref('All');const selected=ref<string|null>(null)
const filtered=computed(()=>props.orders.filter(o=>{const q=query.value.trim().toLowerCase();return(!q||[o.orderNumber,o.customerName,...o.items.map(i=>i.serviceName)].some(v=>v.toLowerCase().includes(q)))&&(commercial.value==='All'||o.commercialStatus===commercial.value)&&(fulfillment.value==='All'||o.fulfillmentStatus===fulfillment.value)&&(payment.value==='All'||o.paymentStatus===payment.value)&&(priority.value==='All'||o.priority===priority.value)}))
function money(v:number){return formatMoney(v,props.currencyUnit)}
function tone(v:string):Tone{return v==='Confirmed'||v==='In Production'?'blue':v==='Closed'||v==='Delivered'||v==='Paid'||v==='Ready'?'green':v==='Cancelled'?'red':v==='Partially Paid'?'amber':'slate'}
function itemSummary(o:OrderRecord){return o.items.map(i=>i.serviceName).join(' · ')||'No configured items'}
function clear(){query.value='';commercial.value=fulfillment.value=payment.value=priority.value='All'}
</script>
<template><div class="orders-view">
  <WorkspaceStickyStack><header class="workspace-heading orders-heading"><div><p class="eyebrow">Sales / operational queue</p><h1>Orders</h1><p class="heading-description">Track persisted customer orders and their independent state axes.</p></div><button class="button button-primary" type="button" @click="emit('new-order')"><Plus :size="16" :stroke-width="1.8" aria-hidden="true"/>New order</button></header>
    <section class="orders-filter-bar panel" aria-label="Order filters"><label class="orders-search"><span class="sr-only">Search orders</span><Search :size="16" aria-hidden="true"/><input v-model="query" type="search" placeholder="Search order, customer, or service"/></label><label class="filter-control"><span>Commercial</span><span class="select-control"><select v-model="commercial"><option>All</option><option>Draft</option><option>Confirmed</option><option>Closed</option><option>Cancelled</option></select><ChevronDown class="select-chevron" :size="14"/></span></label><label class="filter-control"><span>Fulfillment</span><span class="select-control"><select v-model="fulfillment"><option>All</option><option>Pending</option><option>In Production</option><option>Ready</option><option>Delivered</option></select><ChevronDown class="select-chevron" :size="14"/></span></label><label class="filter-control"><span>Payment</span><span class="select-control"><select v-model="payment"><option>All</option><option>Unpaid</option><option>Partially Paid</option><option>Paid</option></select><ChevronDown class="select-chevron" :size="14"/></span></label><label class="filter-control"><span>Priority</span><span class="select-control"><select v-model="priority"><option>All</option><option>Urgent</option><option>High</option><option>Normal</option><option>Low</option></select><ChevronDown class="select-chevron" :size="14"/></span></label><button v-if="query||commercial!=='All'||fulfillment!=='All'||payment!=='All'||priority!=='All'" class="filter-clear" @click="clear">Clear</button><span class="filter-result">{{ filtered.length }} of {{ props.orders.length }} orders</span></section>
  </WorkspaceStickyStack>
  <section class="orders-list-panel panel"><header class="orders-list-heading"><div><h2 class="panel-title">All orders</h2><p class="panel-subtitle">Open an order to inspect its accepted pricing snapshots.</p></div><span class="orders-state-key"><span class="state-key-dot"/>Independent state axes</span></header>
    <div v-if="loading" class="workspace-state">Loading orders…</div><div v-else-if="error" class="workspace-state state-error">{{ error }}</div><div v-else-if="!filtered.length" class="workspace-state"><SearchX :size="22" aria-hidden="true"/><strong>{{ props.orders.length?'No orders match these filters':'No persisted orders yet' }}</strong><button v-if="props.orders.length" class="button button-secondary" @click="clear">Clear filters</button></div>
    <div v-else class="table-wrap orders-table-wrap"><table class="data-table orders-table"><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Created</th><th>Promised</th><th class="numeric-column">Total</th><th>Commercial</th><th>Fulfillment</th><th>Payment</th><th>Priority</th></tr></thead><tbody><tr v-for="order in filtered" :key="order.id" :class="{'is-selected':selected===order.id}" tabindex="0" @click="selected=order.id" @dblclick="emit('open-order',order.id)" @keydown.enter="emit('open-order',order.id)"><td><button class="order-link" @click.stop="emit('open-order',order.id)">{{ order.orderNumber }}</button></td><td><span class="table-primary">{{ order.customerName||'Walk-in customer' }}</span><span class="table-secondary">{{ order.customerPhone||'No contact details' }}</span></td><td><span class="table-primary item-summary">{{ itemSummary(order) }}</span><span class="table-secondary">{{ order.items.length }} line items</span></td><td>{{ formatDateTime(order.createdAt) }}</td><td>{{ order.promisedAt?formatDateTime(order.promisedAt):'—' }}</td><td class="numeric-column">{{ money(order.totalRial) }}</td><td><StatusBadge :label="order.commercialStatus" :tone="tone(order.commercialStatus)"/></td><td><StatusBadge :label="order.fulfillmentStatus" :tone="tone(order.fulfillmentStatus)"/></td><td><StatusBadge :label="order.paymentStatus" :tone="tone(order.paymentStatus)"/></td><td><StatusBadge :label="order.priority" :tone="tone(order.priority)"/></td></tr></tbody></table></div>
  </section>
</div></template>
