<script setup lang="ts">
import { computed, ref } from 'vue'
import { ChevronDown, Plus, Search, SearchX } from 'lucide-vue-next'
import StatusBadge from '../components/StatusBadge.vue'
import WorkspaceStickyStack from '../components/WorkspaceStickyStack.vue'
import type { QuoteRecord } from '../api/quotes'
import { formatMoney, type CurrencyUnit } from '../utils/currency'
import { formatDateTime } from '../utils/date'
const props=defineProps<{quotes:QuoteRecord[];currencyUnit:CurrencyUnit;loading?:boolean;error?:string}>();const emit=defineEmits<{openQuote:[id:string];newQuote:[]}>();const query=ref('');const status=ref('All')
const filtered=computed(()=>props.quotes.filter(q=>(!query.value.trim()||[q.quoteNumber,q.customerName,...q.items.map(i=>i.serviceName)].some(v=>v.toLowerCase().includes(query.value.trim().toLowerCase())))&&(status.value==='All'||q.status===status.value)))
function tone(v:string){return v==='Accepted'||v==='Converted'?'green':v==='Sent'?'blue':v==='Rejected'?'red':v==='Expired'?'amber':'slate'}
</script>
<template><div class="orders-view"><WorkspaceStickyStack><header class="workspace-heading orders-heading"><div><p class="eyebrow">Sales / commercial workspace</p><h1>Quotes</h1><p class="heading-description">Prepare saved offers with immutable pricing snapshots.</p></div><button class="button button-primary" @click="emit('newQuote')"><Plus :size="16"/>New quote</button></header><section class="orders-filter-bar panel quote-filter-bar"><label class="orders-search"><span class="sr-only">Search quotes</span><Search :size="16"/><input v-model="query" type="search" placeholder="Search quote, customer, or service"/></label><label class="filter-control"><span>Status</span><span class="select-control"><select v-model="status"><option>All</option><option>Draft</option><option>Sent</option><option>Accepted</option><option>Rejected</option><option>Expired</option><option>Converted</option></select><ChevronDown class="select-chevron" :size="14"/></span></label><span class="filter-result">{{ filtered.length }} of {{ props.quotes.length }} quotes</span></section></WorkspaceStickyStack><section class="orders-list-panel panel"><header class="orders-list-heading"><div><h2 class="panel-title">Quote register</h2><p class="panel-subtitle">Reopen a quote to inspect the exact accepted snapshots.</p></div></header><div v-if="loading" class="workspace-state">Loading quotes…</div><div v-else-if="error" class="workspace-state state-error">{{ error }}</div><div v-else-if="!filtered.length" class="workspace-state"><SearchX :size="22"/><strong>{{ props.quotes.length?'No quotes match this filter':'No saved quotes yet' }}</strong></div><div v-else class="table-wrap orders-table-wrap"><table class="data-table orders-table quotes-table"><thead><tr><th>Quote</th><th>Customer</th><th>Items</th><th>Created</th><th>Expiry</th><th class="numeric-column">Total</th><th>Status</th></tr></thead><tbody><tr v-for="quote in filtered" :key="quote.id" tabindex="0" @dblclick="emit('openQuote',quote.id)" @keydown.enter="emit('openQuote',quote.id)"><td><button class="order-link" @click.stop="emit('openQuote',quote.id)">{{ quote.quoteNumber }}</button></td><td><span class="table-primary">{{ quote.customerName||'Walk-in customer' }}</span><span class="table-secondary">{{ quote.customerPhone||'No contact details' }}</span></td><td><span class="table-primary item-summary">{{ quote.items.map(i=>i.serviceName).join(' · ')||'No configured items' }}</span><span class="table-secondary">{{ quote.items.length }} line items</span></td><td>{{ formatDateTime(quote.createdAt) }}</td><td>{{ quote.expiryDate?formatDateTime(quote.expiryDate):'—' }}</td><td class="numeric-column">{{ formatMoney(quote.totalRial,currencyUnit) }}</td><td><StatusBadge :label="quote.status" :tone="tone(quote.status)"/></td></tr></tbody></table></div></section></div></template>
