<script setup lang="ts">
import { computed, ref } from 'vue'
import { Plus, SearchX } from 'lucide-vue-next'
import StatusBadge from '../components/StatusBadge.vue'
import WorkspaceStickyStack from '../components/WorkspaceStickyStack.vue'
import SearchField from '../components/SearchField.vue'
import SelectField from '../components/SelectField.vue'
import type { QuoteRecord } from '../api/quotes'
import { formatMoney, type CurrencyUnit } from '../utils/currency'
import { formatDateTime } from '../utils/date'
const props=defineProps<{quotes:QuoteRecord[];currencyUnit:CurrencyUnit;loading?:boolean;error?:string}>();const emit=defineEmits<{openQuote:[id:string];newQuote:[]}>();const query=ref('');const status=ref('All')
const filtered=computed(()=>props.quotes.filter(q=>(!query.value.trim()||[q.quoteNumber,q.customerName,...q.items.map(i=>i.serviceName)].some(v=>v.toLowerCase().includes(query.value.trim().toLowerCase())))&&(status.value==='All'||q.status===status.value)))
function tone(v:string){return v==='Accepted'||v==='Converted'?'green':v==='Sent'?'blue':v==='Rejected'?'red':v==='Expired'?'amber':'slate'}
</script>
<template><div><WorkspaceStickyStack><header><div><p>Sales / commercial workspace</p><h1>Quotes</h1><p>Prepare saved offers with immutable pricing snapshots.</p></div><button class="btn btn-ghost" @click="emit('newQuote')"><Plus :size="16"/>New quote</button></header><section class="grid gap-3 sm:grid-cols-[minmax(0,1fr)_12rem_auto] sm:items-end"><SearchField v-model="query" label="Search quotes" placeholder="Search quote, customer, or service"/><SelectField v-model="status" label="Status" :options="['All', 'Draft', 'Sent', 'Accepted', 'Rejected', 'Expired', 'Converted'].map((value) => ({ label: value, value }))"/><span class="self-end pb-2">{{ filtered.length }} of {{ props.quotes.length }} quotes</span></section></WorkspaceStickyStack><section><header><div><h2>Quote register</h2><p>Reopen a quote to inspect the exact accepted snapshots.</p></div></header><div v-if="loading">Loading quotes…</div><div v-else-if="error">{{ error }}</div><div v-else-if="!filtered.length"><SearchX :size="22"/><strong>{{ props.quotes.length?'No quotes match this filter':'No saved quotes yet' }}</strong></div><div v-else class="overflow-x-auto"><table class="table table-zebra w-full"><thead><tr><th>Quote</th><th>Customer</th><th>Items</th><th>Created</th><th>Expiry</th><th>Total</th><th>Status</th></tr></thead><tbody><tr v-for="quote in filtered" :key="quote.id" tabindex="0" @dblclick="emit('openQuote',quote.id)" @keydown.enter="emit('openQuote',quote.id)"><td><button class="btn btn-ghost" @click.stop="emit('openQuote',quote.id)">{{ quote.quoteNumber }}</button></td><td><span>{{ quote.customerName||'Walk-in customer' }}</span><span>{{ quote.customerPhone||'No contact details' }}</span></td><td><span>{{ quote.items.map(i=>i.serviceName).join(' · ')||'No configured items' }}</span><span>{{ quote.items.length }} line items</span></td><td>{{ formatDateTime(quote.createdAt) }}</td><td>{{ quote.expiryDate?formatDateTime(quote.expiryDate):'—' }}</td><td>{{ formatMoney(quote.totalRial,currencyUnit) }}</td><td><StatusBadge :label="quote.status" :tone="tone(quote.status)"/></td></tr></tbody></table></div></section></div></template>
