<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { BarChart3, FileText, Printer, RefreshCw } from 'lucide-vue-next'
import SectionPanel from '../components/SectionPanel.vue'
import WorkspaceStickyStack from '../components/WorkspaceStickyStack.vue'
import JalaliDatePicker from '../components/JalaliDatePicker.vue'
import StatusBadge from '../components/StatusBadge.vue'
import { reportsApi, type PrintDocumentRecord, type ReportRecord } from '../api/reports'
import { formatMoney } from '../utils/currency'
import { formatDate, formatDateTime, currentCanonicalDate } from '../utils/date'
import { normalizeError } from '../ui/feedback'
import SelectField from '../components/SelectField.vue'
const props=defineProps<{currencyUnit:'Rial'|'Toman'}>();const emit=defineEmits<{notify:[message:string]}>()
const tabs=[['profit_loss','P&L'],['cash_bank','Cash / Bank'],['receivables','Receivables'],['payables','Payables'],['expenses','Expenses'],['inventory','Inventory'],['sales_by_service','Sales by service'],['customer_sales','Customer sales'],['material_usage','Material use / waste'],['production','Production']]
const activeTab=ref('profit_loss');const end=ref<string|null>(currentCanonicalDate());const start=ref<string|null>(new Date(Date.now()-30*86400000).toISOString().slice(0,10));const report=ref<ReportRecord|null>(null);const loading=ref(false);const error=ref('');const printKind=ref('invoice');const printID=ref('');const partyID=ref('');const printDoc=ref<PrintDocumentRecord|null>(null)
const summary=computed(()=>report.value?.summaries??[]);const money=(v:number)=>formatMoney(v,props.currencyUnit);const quantity=(v:number)=>v?String(v/1000000):'0'
async function load(){loading.value=true;error.value='';try{report.value=await reportsApi.report(activeTab.value,start.value||'',end.value||'')}catch(e){error.value=normalizeError(e).message}finally{loading.value=false}}
async function loadPrint(){if(!printID.value&&!printKind.value.includes('statement')){emit('notify','Enter a source record ID first.');return}try{printDoc.value=await reportsApi.print(printKind.value,printID.value,start.value||'',end.value||'',partyID.value)}catch(e){emit('notify',`Error: ${normalizeError(e).message}`)}}
function print(){if(printDoc.value)window.print()};onMounted(load);watch([activeTab,start,end],load)
</script>
<template>
<div><WorkspaceStickyStack><header><div><p>Insights · authoritative queries</p><h1>Reports</h1><p>Reconciled views of journals, movements, production, and saved documents.</p></div><div><button class="btn btn-ghost" type="button" @click="load"><RefreshCw :size="15"/> Refresh</button></div></header></WorkspaceStickyStack>
<div><div role="tablist"><button class="btn btn-sm" v-for="tab in tabs" :key="tab[0]" :class="activeTab===tab[0] ? 'btn-primary' : 'btn-ghost'" type="button" @click="activeTab=tab[0]"><BarChart3 :size="14"/>{{tab[1]}}</button></div><div><label class="form-control gap-1">From <JalaliDatePicker v-model="start"/></label><label class="form-control gap-1">To <JalaliDatePicker v-model="end"/></label></div></div>
<p v-if="error">{{error}}</p><div><article v-for="item in summary" :key="item.key"><span>{{item.label}}</span><strong>{{money(item.amountRial)}}</strong><small v-if="item.count">{{item.count}} records</small></article><article v-if="loading"><span>Loading</span><strong>…</strong></article></div>
<SectionPanel :title="tabs.find(t=>t[0]===activeTab)?.[1]||'Report'" :subtitle="`${report?.startDate||''} → ${report?.endDate||''} · values supplied by Go`"><div><table class="table table-zebra w-full"><thead><tr><th>Source / name</th><th>Category</th><th>Status</th><th>Quantity</th><th>Amount</th><th>Secondary</th></tr></thead><tbody><tr v-for="row in report?.rows" :key="`${row.id}-${row.name}`"><td><span>{{row.name||row.id}}</span><span v-if="row.referenceId">{{row.referenceId}}</span></td><td>{{row.category||'—'}}</td><td><StatusBadge v-if="row.status" :label="row.status" tone="slate"/><span v-else>—</span></td><td>{{row.quantityUnits?quantity(row.quantityUnits):'—'}}<span v-if="row.secondaryQuantityUnits"> / {{quantity(row.secondaryQuantityUnits)}}</span></td><td>{{money(row.amountRial)}}</td><td>{{row.secondaryAmountRial?money(row.secondaryAmountRial):'—'}}</td></tr><tr v-if="!loading&&!report?.rows?.length"><td colspan="6">No persisted records in this range.</td></tr></tbody></table></div></SectionPanel>
<SectionPanel title="Print preview" subtitle="Source data is loaded from immutable saved records"><div><SelectField v-model="printKind" label="Document" :options="[{ label: 'Quote', value: 'quote' }, { label: 'Invoice', value: 'invoice' }, { label: 'Payment receipt', value: 'payment_receipt' }, { label: 'Customer statement', value: 'customer_statement' }, { label: 'Supplier statement', value: 'supplier_statement' }]" /><label class="form-control gap-1" v-if="!printKind.includes('statement')">Record ID<input class="input input-bordered w-full min-w-0" v-model="printID" placeholder="e.g. INV-..."/></label><label class="form-control gap-1" v-else>Party ID<input class="input input-bordered w-full min-w-0" v-model="partyID" placeholder="Customer or supplier ID"/></label><button class="btn btn-ghost" type="button" @click="loadPrint"><FileText :size="15"/> Load preview</button><button class="btn btn-ghost" v-if="printDoc" type="button" @click="print"><Printer :size="15"/> Print</button></div><article v-if="printDoc"><header><div><h2>{{printDoc.shop.shopName}}</h2><p>{{printDoc.shop.shopSubtitle}}</p><p>{{printDoc.shop.address}} · {{printDoc.shop.phone}}</p></div><div><strong>{{printDoc.kind.replace('_',' ')}}</strong><span>{{printDoc.number}}</span><span>{{formatDate(printDoc.date)}}</span></div></header><div><strong>{{printDoc.customerName||printDoc.supplierName}}</strong><span>{{printDoc.customerContact}}</span><span v-if="printDoc.reference">Reference: {{printDoc.reference}}</span></div><table class="table table-zebra w-full" v-if="printDoc.lines.length"><thead><tr><th>Description</th><th>Qty</th><th>Unit price</th><th>Total</th></tr></thead><tbody><tr v-for="line in printDoc.lines" :key="line.description"><td>{{line.description}}</td><td>{{line.quantityUnits/1000000}} {{line.unit}}</td><td>{{money(line.unitPriceRial)}}</td><td>{{money(line.lineTotalRial)}}</td></tr></tbody></table><table class="table table-zebra w-full" v-if="printDoc.statementLines.length"><thead><tr><th>Date</th><th>Reference</th><th>Description</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody><tr v-for="line in printDoc.statementLines" :key="`${line.date}-${line.reference}-${line.description}`"><td>{{line.date?formatDateTime(line.date):'—'}}</td><td>{{line.reference}}</td><td>{{line.description}}</td><td>{{money(line.debitRial)}}</td><td>{{money(line.creditRial)}}</td><td>{{money(line.balanceRial)}}</td></tr></tbody></table><div><span>Total</span><strong>{{money(printDoc.totalRial||printDoc.amountRial)}}</strong></div><p>{{printDoc.notes||printDoc.shop.documentFooter}}</p></article></SectionPanel>
</div></template>
