<script setup lang="ts">
import { onMounted, ref } from 'vue'
import SectionPanel from '../components/SectionPanel.vue'
import WorkspaceStickyStack from '../components/WorkspaceStickyStack.vue'
import { reportsApi, type ShopSettingsRecord } from '../api/reports'
const emit=defineEmits<{notify:[message:string]}>();const form=ref<ShopSettingsRecord>({shopName:'',shopSubtitle:'',phone:'',address:'',email:'',website:'',registrationId:'',taxId:'',logoPath:'',documentFooter:'',documentNotes:''});const loading=ref(true)
onMounted(async()=>{try{form.value=await reportsApi.settings()}catch(e){emit('notify',String(e))}finally{loading.value=false}});async function save(){try{await reportsApi.saveSettings(form.value);emit('notify','Document identity saved.')}catch(e){emit('notify',String(e))}}
</script>
<template><div class="settings-view"><WorkspaceStickyStack><header class="workspace-heading"><div><p class="eyebrow">Insights & setup</p><h1>Shop settings</h1><p class="heading-description">Identity and notes used by printable documents.</p></div><button class="button button-primary" type="button" :disabled="loading" @click="save">Save settings</button></header></WorkspaceStickyStack><SectionPanel title="Document identity" subtitle="Logo path is metadata only; file blobs remain outside SQLite"><div class="settings-grid"><label>Shop name<input v-model="form.shopName"/></label><label>Subtitle<input v-model="form.shopSubtitle"/></label><label>Phone<input v-model="form.phone"/></label><label>Email<input v-model="form.email" type="email"/></label><label>Website<input v-model="form.website"/></label><label>Logo path<input v-model="form.logoPath"/></label><label class="settings-wide">Address<textarea v-model="form.address" rows="2"/></label><label>Registration ID<input v-model="form.registrationId"/></label><label>Tax ID<input v-model="form.taxId"/></label><label class="settings-wide">Default footer<textarea v-model="form.documentFooter" rows="2"/></label><label class="settings-wide">Default notes<textarea v-model="form.documentNotes" rows="2"/></label></div></SectionPanel></div></template>
