<script setup lang="ts">
import { onMounted, ref } from 'vue'
import SectionPanel from '../components/SectionPanel.vue'
import WorkspaceStickyStack from '../components/WorkspaceStickyStack.vue'
import { reportsApi, type BackupInfoRecord, type DataPathsRecord, type ShopSettingsRecord } from '../api/reports'
const emit=defineEmits<{notify:[message:string]}>();const form=ref<ShopSettingsRecord>({shopName:'',shopSubtitle:'',phone:'',address:'',email:'',website:'',registrationId:'',taxId:'',logoPath:'',documentFooter:'',documentNotes:''});const loading=ref(true);const backupBusy=ref(false);const backupPath=ref('');const paths=ref<DataPathsRecord|null>(null);const lastBackup=ref<BackupInfoRecord|null>(null)
onMounted(async()=>{try{const [settings,dataPaths]=await Promise.all([reportsApi.settings(),reportsApi.dataPaths()]);form.value=settings;paths.value=dataPaths;try{lastBackup.value=await reportsApi.lastBackup()}catch{/* no backup yet */}}catch(e){emit('notify',String(e))}finally{loading.value=false}});async function save(){try{await reportsApi.saveSettings(form.value);emit('notify','Document identity saved.')}catch(e){emit('notify',String(e))}}
async function createBackup(){backupBusy.value=true;try{lastBackup.value=await reportsApi.createBackup();backupPath.value=lastBackup.value.path;emit('notify','Backup created and verified.')}catch(e){emit('notify',String(e))}finally{backupBusy.value=false}}
async function chooseBackup(){try{const path=await reportsApi.selectBackupFile();if(path)backupPath.value=path}catch(e){emit('notify',String(e))}}
async function verifyBackup(){if(!backupPath.value)return;backupBusy.value=true;try{lastBackup.value=await reportsApi.verifyBackup(backupPath.value);emit('notify','Backup is valid.')}catch(e){emit('notify',String(e))}finally{backupBusy.value=false}}
async function restoreBackup(){if(!backupPath.value||!window.confirm('Restore this backup? The current application data will be replaced after validation.'))return;backupBusy.value=true;try{lastBackup.value=await reportsApi.restoreBackup(backupPath.value);emit('notify','Backup restored successfully.')}catch(e){emit('notify',String(e))}finally{backupBusy.value=false}}
</script>
<template><div class="settings-view"><WorkspaceStickyStack><header class="workspace-heading"><div><p class="eyebrow">Insights & setup</p><h1>Shop settings</h1><p class="heading-description">Identity, data safety, and notes used by printable documents.</p></div><button class="button button-primary" type="button" :disabled="loading" @click="save">Save settings</button></header></WorkspaceStickyStack><SectionPanel title="Document identity" subtitle="Logo path is metadata only; file blobs remain outside SQLite"><div class="settings-grid"><label>Shop name<input v-model="form.shopName"/></label><label>Subtitle<input v-model="form.shopSubtitle"/></label><label>Phone<input v-model="form.phone"/></label><label>Email<input v-model="form.email" type="email"/></label><label>Website<input v-model="form.website"/></label><label>Logo path<input v-model="form.logoPath"/></label><label class="settings-wide">Address<textarea v-model="form.address" rows="2"/></label><label>Registration ID<input v-model="form.registrationId"/></label><label>Tax ID<input v-model="form.taxId"/></label><label class="settings-wide">Default footer<textarea v-model="form.documentFooter" rows="2"/></label><label class="settings-wide">Default notes<textarea v-model="form.documentNotes" rows="2"/></label></div></SectionPanel><SectionPanel title="Backup & restore" subtitle="Backups include a consistent SQLite snapshot and Atropaten-managed files"><div class="backup-status" v-if="paths"><div><span>Data location</span><strong>{{ paths.root }}</strong></div><div><span>Database</span><strong>{{ paths.database }}</strong></div><div><span>Application / schema</span><strong>{{ paths.applicationVersion }} · v{{ paths.schemaVersion }}</strong></div><div><span>Backups folder</span><strong>{{ paths.backups }}</strong></div></div><div class="backup-actions"><button class="button button-primary" type="button" :disabled="backupBusy" @click="createBackup">Create backup</button><button class="button button-secondary" type="button" :disabled="backupBusy||!backupPath" @click="verifyBackup">Verify selected</button><button class="button button-secondary" type="button" :disabled="backupBusy" @click="chooseBackup">Choose backup</button><button class="button button-secondary" type="button" :disabled="backupBusy||!backupPath" @click="restoreBackup">Restore selected</button></div><label class="backup-path">Selected backup<input v-model="backupPath" placeholder="Choose an .zip backup"/></label><p v-if="lastBackup" class="backup-meta">{{ lastBackup.path }} · schema v{{ lastBackup.schemaVersion }} · {{ lastBackup.managedFileCount }} managed file(s)</p></SectionPanel></div></template>
